// Code generated by Kitex v0.16.1. DO NOT EDIT.

package messageservice

import (
	common "Noah/kitex_gen/common"
	message "Noah/kitex_gen/message"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, req *message.SendMessageReq, callOptions ...callopt.Option) (r *message.MessageResp, err error)
	BatchSendMessage(ctx context.Context, req *message.BatchSendMessageReq, callOptions ...callopt.Option) (r *message.BatchMessageResp, err error)
	Subscribe(ctx context.Context, req *message.SubscribeReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	ConsumeMessages(ctx context.Context, req *message.ConsumeMessageReq, callOptions ...callopt.Option) (r *message.ConsumeMessageResp, err error)
	AcknowledgeMessage(ctx context.Context, req *message.AcknowledgeMessageReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	BatchAcknowledgeMessages(ctx context.Context, req *message.BatchAcknowledgeMessageReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetMessageStats(ctx context.Context, callOptions ...callopt.Option) (r *message.MessageStatsResp, err error)
	CreateTopic(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	DeleteTopic(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	ClearMessages(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) SendMessage(ctx context.Context, req *message.SendMessageReq, callOptions ...callopt.Option) (r *message.MessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, req)
}

func (p *kMessageServiceClient) BatchSendMessage(ctx context.Context, req *message.BatchSendMessageReq, callOptions ...callopt.Option) (r *message.BatchMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchSendMessage(ctx, req)
}

func (p *kMessageServiceClient) Subscribe(ctx context.Context, req *message.SubscribeReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Subscribe(ctx, req)
}

func (p *kMessageServiceClient) ConsumeMessages(ctx context.Context, req *message.ConsumeMessageReq, callOptions ...callopt.Option) (r *message.ConsumeMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConsumeMessages(ctx, req)
}

func (p *kMessageServiceClient) AcknowledgeMessage(ctx context.Context, req *message.AcknowledgeMessageReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcknowledgeMessage(ctx, req)
}

func (p *kMessageServiceClient) BatchAcknowledgeMessages(ctx context.Context, req *message.BatchAcknowledgeMessageReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchAcknowledgeMessages(ctx, req)
}

func (p *kMessageServiceClient) GetMessageStats(ctx context.Context, callOptions ...callopt.Option) (r *message.MessageStatsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMessageStats(ctx)
}

func (p *kMessageServiceClient) CreateTopic(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTopic(ctx, topic)
}

func (p *kMessageServiceClient) DeleteTopic(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTopic(ctx, topic)
}

func (p *kMessageServiceClient) ClearMessages(ctx context.Context, topic message.Topic, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearMessages(ctx, topic)
}
