apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: logos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: docker.1panel.live/bitnami/etcd:latest
          ports:
            - containerPort: 2379
            - containerPort: 2380
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: etcd-data
              mountPath: /bitnami/etcd
      volumes:
        - name: etcd-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: logos
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: peer
      port: 2380
      targetPort: 2380
