// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ai/summary.proto

package summary

import (
	chat "Logos/proto_gen/chat"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 待办事项
type TodoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Assignee      string                 `protobuf:"bytes,3,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_ai_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{0}
}

func (x *TodoItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TodoItem) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

func (x *TodoItem) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TodoItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 回复候选
type ReplyCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCandidate) Reset() {
	*x = ReplyCandidate{}
	mi := &file_ai_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCandidate) ProtoMessage() {}

func (x *ReplyCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCandidate.ProtoReflect.Descriptor instead.
func (*ReplyCandidate) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyCandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplyCandidate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyCandidate) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ReplyCandidate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 总结请求
type SummarizeMessagesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChatId            string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType          chat.ChatType          `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=messaging.chat.ChatType" json:"chat_type,omitempty"`
	MessageIds        []string               `protobuf:"bytes,3,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IncludeTodos      bool                   `protobuf:"varint,6,opt,name=include_todos,json=includeTodos,proto3" json:"include_todos,omitempty"`
	IncludeCandidates bool                   `protobuf:"varint,7,opt,name=include_candidates,json=includeCandidates,proto3" json:"include_candidates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SummarizeMessagesRequest) Reset() {
	*x = SummarizeMessagesRequest{}
	mi := &file_ai_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeMessagesRequest) ProtoMessage() {}

func (x *SummarizeMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeMessagesRequest.ProtoReflect.Descriptor instead.
func (*SummarizeMessagesRequest) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizeMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SummarizeMessagesRequest) GetChatType() chat.ChatType {
	if x != nil {
		return x.ChatType
	}
	return chat.ChatType(0)
}

func (x *SummarizeMessagesRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *SummarizeMessagesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SummarizeMessagesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SummarizeMessagesRequest) GetIncludeTodos() bool {
	if x != nil {
		return x.IncludeTodos
	}
	return false
}

func (x *SummarizeMessagesRequest) GetIncludeCandidates() bool {
	if x != nil {
		return x.IncludeCandidates
	}
	return false
}

// 总结响应
type SummarizeMessagesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Todos           []*TodoItem            `protobuf:"bytes,4,rep,name=todos,proto3" json:"todos,omitempty"`
	ReplyCandidates []*ReplyCandidate      `protobuf:"bytes,5,rep,name=reply_candidates,json=replyCandidates,proto3" json:"reply_candidates,omitempty"`
	KeyPoints       []string               `protobuf:"bytes,6,rep,name=key_points,json=keyPoints,proto3" json:"key_points,omitempty"`
	Participants    []string               `protobuf:"bytes,7,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SummarizeMessagesResponse) Reset() {
	*x = SummarizeMessagesResponse{}
	mi := &file_ai_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeMessagesResponse) ProtoMessage() {}

func (x *SummarizeMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeMessagesResponse.ProtoReflect.Descriptor instead.
func (*SummarizeMessagesResponse) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{3}
}

func (x *SummarizeMessagesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SummarizeMessagesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SummarizeMessagesResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeMessagesResponse) GetTodos() []*TodoItem {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *SummarizeMessagesResponse) GetReplyCandidates() []*ReplyCandidate {
	if x != nil {
		return x.ReplyCandidates
	}
	return nil
}

func (x *SummarizeMessagesResponse) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *SummarizeMessagesResponse) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

// 生成回复候选请求
type GenerateReplyCandidatesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChatId            string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType          chat.ChatType          `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=messaging.chat.ChatType" json:"chat_type,omitempty"`
	ContextMessageIds []string               `protobuf:"bytes,3,rep,name=context_message_ids,json=contextMessageIds,proto3" json:"context_message_ids,omitempty"`
	CandidateCount    int32                  `protobuf:"varint,4,opt,name=candidate_count,json=candidateCount,proto3" json:"candidate_count,omitempty"`
	Tone              string                 `protobuf:"bytes,5,opt,name=tone,proto3" json:"tone,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateReplyCandidatesRequest) Reset() {
	*x = GenerateReplyCandidatesRequest{}
	mi := &file_ai_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReplyCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReplyCandidatesRequest) ProtoMessage() {}

func (x *GenerateReplyCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReplyCandidatesRequest.ProtoReflect.Descriptor instead.
func (*GenerateReplyCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateReplyCandidatesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GenerateReplyCandidatesRequest) GetChatType() chat.ChatType {
	if x != nil {
		return x.ChatType
	}
	return chat.ChatType(0)
}

func (x *GenerateReplyCandidatesRequest) GetContextMessageIds() []string {
	if x != nil {
		return x.ContextMessageIds
	}
	return nil
}

func (x *GenerateReplyCandidatesRequest) GetCandidateCount() int32 {
	if x != nil {
		return x.CandidateCount
	}
	return 0
}

func (x *GenerateReplyCandidatesRequest) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

// 生成回复候选响应
type GenerateReplyCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Candidates    []*ReplyCandidate      `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReplyCandidatesResponse) Reset() {
	*x = GenerateReplyCandidatesResponse{}
	mi := &file_ai_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReplyCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReplyCandidatesResponse) ProtoMessage() {}

func (x *GenerateReplyCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReplyCandidatesResponse.ProtoReflect.Descriptor instead.
func (*GenerateReplyCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateReplyCandidatesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateReplyCandidatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateReplyCandidatesResponse) GetCandidates() []*ReplyCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// 提取待办事项请求
type ExtractTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType      chat.ChatType          `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=messaging.chat.ChatType" json:"chat_type,omitempty"`
	MessageIds    []string               `protobuf:"bytes,3,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTodosRequest) Reset() {
	*x = ExtractTodosRequest{}
	mi := &file_ai_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTodosRequest) ProtoMessage() {}

func (x *ExtractTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTodosRequest.ProtoReflect.Descriptor instead.
func (*ExtractTodosRequest) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractTodosRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ExtractTodosRequest) GetChatType() chat.ChatType {
	if x != nil {
		return x.ChatType
	}
	return chat.ChatType(0)
}

func (x *ExtractTodosRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// 提取待办事项响应
type ExtractTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Todos         []*TodoItem            `protobuf:"bytes,3,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTodosResponse) Reset() {
	*x = ExtractTodosResponse{}
	mi := &file_ai_summary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTodosResponse) ProtoMessage() {}

func (x *ExtractTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_summary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTodosResponse.ProtoReflect.Descriptor instead.
func (*ExtractTodosResponse) Descriptor() ([]byte, []int) {
	return file_ai_summary_proto_rawDescGZIP(), []int{7}
}

func (x *ExtractTodosResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExtractTodosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExtractTodosResponse) GetTodos() []*TodoItem {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_ai_summary_proto protoreflect.FileDescriptor

const file_ai_summary_proto_rawDesc = "" +
	"\n" +
	"\x10ai/summary.proto\x12\n" +
	"ai.summary\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14messaging/chat.proto\"\xa0\x01\n" +
	"\bTodoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bassignee\x18\x03 \x01(\tR\bassignee\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"n\n" +
	"\x0eReplyCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xd1\x02\n" +
	"\x18SummarizeMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x125\n" +
	"\tchat_type\x18\x02 \x01(\x0e2\x18.messaging.chat.ChatTypeR\bchatType\x12\x1f\n" +
	"\vmessage_ids\x18\x03 \x03(\tR\n" +
	"messageIds\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12#\n" +
	"\rinclude_todos\x18\x06 \x01(\bR\fincludeTodos\x12-\n" +
	"\x12include_candidates\x18\a \x01(\bR\x11includeCandidates\"\x99\x02\n" +
	"\x19SummarizeMessagesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12*\n" +
	"\x05todos\x18\x04 \x03(\v2\x14.ai.summary.TodoItemR\x05todos\x12E\n" +
	"\x10reply_candidates\x18\x05 \x03(\v2\x1a.ai.summary.ReplyCandidateR\x0freplyCandidates\x12\x1d\n" +
	"\n" +
	"key_points\x18\x06 \x03(\tR\tkeyPoints\x12\"\n" +
	"\fparticipants\x18\a \x03(\tR\fparticipants\"\xdd\x01\n" +
	"\x1eGenerateReplyCandidatesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x125\n" +
	"\tchat_type\x18\x02 \x01(\x0e2\x18.messaging.chat.ChatTypeR\bchatType\x12.\n" +
	"\x13context_message_ids\x18\x03 \x03(\tR\x11contextMessageIds\x12'\n" +
	"\x0fcandidate_count\x18\x04 \x01(\x05R\x0ecandidateCount\x12\x12\n" +
	"\x04tone\x18\x05 \x01(\tR\x04tone\"\x8b\x01\n" +
	"\x1fGenerateReplyCandidatesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x1a.ai.summary.ReplyCandidateR\n" +
	"candidates\"\x86\x01\n" +
	"\x13ExtractTodosRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x125\n" +
	"\tchat_type\x18\x02 \x01(\x0e2\x18.messaging.chat.ChatTypeR\bchatType\x12\x1f\n" +
	"\vmessage_ids\x18\x03 \x03(\tR\n" +
	"messageIds\"p\n" +
	"\x14ExtractTodosResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x05todos\x18\x03 \x03(\v2\x14.ai.summary.TodoItemR\x05todos2\xb9\x02\n" +
	"\x0eSummaryService\x12`\n" +
	"\x11SummarizeMessages\x12$.ai.summary.SummarizeMessagesRequest\x1a%.ai.summary.SummarizeMessagesResponse\x12r\n" +
	"\x17GenerateReplyCandidates\x12*.ai.summary.GenerateReplyCandidatesRequest\x1a+.ai.summary.GenerateReplyCandidatesResponse\x12Q\n" +
	"\fExtractTodos\x12\x1f.ai.summary.ExtractTodosRequest\x1a .ai.summary.ExtractTodosResponseB\x19Z\x17Logos/proto_gen/summaryb\x06proto3"

var (
	file_ai_summary_proto_rawDescOnce sync.Once
	file_ai_summary_proto_rawDescData []byte
)

func file_ai_summary_proto_rawDescGZIP() []byte {
	file_ai_summary_proto_rawDescOnce.Do(func() {
		file_ai_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_summary_proto_rawDesc), len(file_ai_summary_proto_rawDesc)))
	})
	return file_ai_summary_proto_rawDescData
}

var file_ai_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_summary_proto_goTypes = []any{
	(*TodoItem)(nil),                        // 0: ai.summary.TodoItem
	(*ReplyCandidate)(nil),                  // 1: ai.summary.ReplyCandidate
	(*SummarizeMessagesRequest)(nil),        // 2: ai.summary.SummarizeMessagesRequest
	(*SummarizeMessagesResponse)(nil),       // 3: ai.summary.SummarizeMessagesResponse
	(*GenerateReplyCandidatesRequest)(nil),  // 4: ai.summary.GenerateReplyCandidatesRequest
	(*GenerateReplyCandidatesResponse)(nil), // 5: ai.summary.GenerateReplyCandidatesResponse
	(*ExtractTodosRequest)(nil),             // 6: ai.summary.ExtractTodosRequest
	(*ExtractTodosResponse)(nil),            // 7: ai.summary.ExtractTodosResponse
	(*timestamppb.Timestamp)(nil),           // 8: google.protobuf.Timestamp
	(chat.ChatType)(0),                      // 9: messaging.chat.ChatType
}
var file_ai_summary_proto_depIdxs = []int32{
	8,  // 0: ai.summary.TodoItem.deadline:type_name -> google.protobuf.Timestamp
	9,  // 1: ai.summary.SummarizeMessagesRequest.chat_type:type_name -> messaging.chat.ChatType
	8,  // 2: ai.summary.SummarizeMessagesRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 3: ai.summary.SummarizeMessagesRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 4: ai.summary.SummarizeMessagesResponse.todos:type_name -> ai.summary.TodoItem
	1,  // 5: ai.summary.SummarizeMessagesResponse.reply_candidates:type_name -> ai.summary.ReplyCandidate
	9,  // 6: ai.summary.GenerateReplyCandidatesRequest.chat_type:type_name -> messaging.chat.ChatType
	1,  // 7: ai.summary.GenerateReplyCandidatesResponse.candidates:type_name -> ai.summary.ReplyCandidate
	9,  // 8: ai.summary.ExtractTodosRequest.chat_type:type_name -> messaging.chat.ChatType
	0,  // 9: ai.summary.ExtractTodosResponse.todos:type_name -> ai.summary.TodoItem
	2,  // 10: ai.summary.SummaryService.SummarizeMessages:input_type -> ai.summary.SummarizeMessagesRequest
	4,  // 11: ai.summary.SummaryService.GenerateReplyCandidates:input_type -> ai.summary.GenerateReplyCandidatesRequest
	6,  // 12: ai.summary.SummaryService.ExtractTodos:input_type -> ai.summary.ExtractTodosRequest
	3,  // 13: ai.summary.SummaryService.SummarizeMessages:output_type -> ai.summary.SummarizeMessagesResponse
	5,  // 14: ai.summary.SummaryService.GenerateReplyCandidates:output_type -> ai.summary.GenerateReplyCandidatesResponse
	7,  // 15: ai.summary.SummaryService.ExtractTodos:output_type -> ai.summary.ExtractTodosResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ai_summary_proto_init() }
func file_ai_summary_proto_init() {
	if File_ai_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_summary_proto_rawDesc), len(file_ai_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_summary_proto_goTypes,
		DependencyIndexes: file_ai_summary_proto_depIdxs,
		MessageInfos:      file_ai_summary_proto_msgTypes,
	}.Build()
	File_ai_summary_proto = out.File
	file_ai_summary_proto_goTypes = nil
	file_ai_summary_proto_depIdxs = nil
}
