// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: messaging/chat.proto

package chat

import (
	common "Logos/proto_gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TEXT   MessageType = 0
	MessageType_IMAGE  MessageType = 1
	MessageType_FILE   MessageType = 2
	MessageType_SYSTEM MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "FILE",
		3: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":   0,
		"IMAGE":  1,
		"FILE":   2,
		"SYSTEM": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messaging_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messaging_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    *int64                 `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3,oneof" json:"receiver_id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=chat.MessageType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Read          *bool                  `protobuf:"varint,8,opt,name=read,proto3,oneof" json:"read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_messaging_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetReceiverId() int64 {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return 0
}

func (x *ChatMessage) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *ChatMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChatMessage) GetRead() bool {
	if x != nil && x.Read != nil {
		return *x.Read
	}
	return false
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    *int64                 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3,oneof" json:"receiver_id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=chat.MessageType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_messaging_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageReq) GetReceiverId() int64 {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return 0
}

func (x *SendMessageReq) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *SendMessageReq) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *SendMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_messaging_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *SendMessageResp) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceiverId    *int64                 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3,oneof" json:"receiver_id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	BeforeTime    int64                  `protobuf:"varint,4,opt,name=before_time,json=beforeTime,proto3" json:"before_time,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_messaging_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetHistoryReq) GetReceiverId() int64 {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return 0
}

func (x *GetHistoryReq) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GetHistoryReq) GetBeforeTime() int64 {
	if x != nil {
		return x.BeforeTime
	}
	return 0
}

func (x *GetHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	mi := &file_messaging_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *HistoryResp) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *HistoryResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageIds    []string               `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadReq) Reset() {
	*x = MarkReadReq{}
	mi := &file_messaging_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReq) ProtoMessage() {}

func (x *MarkReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReq.ProtoReflect.Descriptor instead.
func (*MarkReadReq) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkReadReq) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type CreateGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MemberIds     []int64                `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_messaging_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGroupReq) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupReq) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type GroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MemberIds     []int64                `protobuf:"varint,4,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResp) Reset() {
	*x = GroupResp{}
	mi := &file_messaging_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResp) ProtoMessage() {}

func (x *GroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResp.ProtoReflect.Descriptor instead.
func (*GroupResp) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GroupResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GroupResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupResp) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type GroupMemberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberReq) Reset() {
	*x = GroupMemberReq{}
	mi := &file_messaging_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberReq) ProtoMessage() {}

func (x *GroupMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_messaging_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberReq.ProtoReflect.Descriptor instead.
func (*GroupMemberReq) Descriptor() ([]byte, []int) {
	return file_messaging_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMemberReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMemberReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_messaging_chat_proto protoreflect.FileDescriptor

const file_messaging_chat_proto_rawDesc = "" +
	"\n" +
	"\x14messaging/chat.proto\x12\x04chat\x1a\fcommon.proto\"\x9f\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12$\n" +
	"\vreceiver_id\x18\x03 \x01(\x03H\x00R\n" +
	"receiverId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x04 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.chat.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\x04read\x18\b \x01(\bH\x02R\x04read\x88\x01\x01B\x0e\n" +
	"\f_receiver_idB\v\n" +
	"\t_group_idB\a\n" +
	"\x05_read\"\xd1\x01\n" +
	"\x0eSendMessageReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12$\n" +
	"\vreceiver_id\x18\x02 \x01(\x03H\x00R\n" +
	"receiverId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.chat.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\x0e\n" +
	"\f_receiver_idB\v\n" +
	"\t_group_id\"m\n" +
	"\x0fSendMessageResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12+\n" +
	"\amessage\x18\x02 \x01(\v2\x11.chat.ChatMessageR\amessage\"\xc2\x01\n" +
	"\rGetHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\vreceiver_id\x18\x02 \x01(\x03H\x00R\n" +
	"receiverId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12\x1f\n" +
	"\vbefore_time\x18\x04 \x01(\x03R\n" +
	"beforeTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\x0e\n" +
	"\f_receiver_idB\v\n" +
	"\t_group_id\"\x86\x01\n" +
	"\vHistoryResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.chat.ChatMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"G\n" +
	"\vMarkReadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\tR\n" +
	"messageIds\"b\n" +
	"\x0eCreateGroupReq\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03R\tmemberIds\"\x88\x01\n" +
	"\tGroupResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x04 \x03(\x03R\tmemberIds\"D\n" +
	"\x0eGroupMemberReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId*8\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\b\n" +
	"\x04FILE\x10\x02\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x032\xe0\x02\n" +
	"\vChatService\x12:\n" +
	"\vSendMessage\x12\x14.chat.SendMessageReq\x1a\x15.chat.SendMessageResp\x12;\n" +
	"\x11GetMessageHistory\x12\x13.chat.GetHistoryReq\x1a\x11.chat.HistoryResp\x127\n" +
	"\x10MarkMessagesRead\x12\x11.chat.MarkReadReq\x1a\x10.common.BaseResp\x124\n" +
	"\vCreateGroup\x12\x14.chat.CreateGroupReq\x1a\x0f.chat.GroupResp\x123\n" +
	"\tJoinGroup\x12\x14.chat.GroupMemberReq\x1a\x10.common.BaseResp\x124\n" +
	"\n" +
	"LeaveGroup\x12\x14.chat.GroupMemberReq\x1a\x10.common.BaseRespB\x16Z\x14Logos/proto_gen/chatb\x06proto3"

var (
	file_messaging_chat_proto_rawDescOnce sync.Once
	file_messaging_chat_proto_rawDescData []byte
)

func file_messaging_chat_proto_rawDescGZIP() []byte {
	file_messaging_chat_proto_rawDescOnce.Do(func() {
		file_messaging_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messaging_chat_proto_rawDesc), len(file_messaging_chat_proto_rawDesc)))
	})
	return file_messaging_chat_proto_rawDescData
}

var file_messaging_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messaging_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messaging_chat_proto_goTypes = []any{
	(MessageType)(0),        // 0: chat.MessageType
	(*ChatMessage)(nil),     // 1: chat.ChatMessage
	(*SendMessageReq)(nil),  // 2: chat.SendMessageReq
	(*SendMessageResp)(nil), // 3: chat.SendMessageResp
	(*GetHistoryReq)(nil),   // 4: chat.GetHistoryReq
	(*HistoryResp)(nil),     // 5: chat.HistoryResp
	(*MarkReadReq)(nil),     // 6: chat.MarkReadReq
	(*CreateGroupReq)(nil),  // 7: chat.CreateGroupReq
	(*GroupResp)(nil),       // 8: chat.GroupResp
	(*GroupMemberReq)(nil),  // 9: chat.GroupMemberReq
	(*common.BaseResp)(nil), // 10: common.BaseResp
}
var file_messaging_chat_proto_depIdxs = []int32{
	0,  // 0: chat.ChatMessage.type:type_name -> chat.MessageType
	0,  // 1: chat.SendMessageReq.type:type_name -> chat.MessageType
	10, // 2: chat.SendMessageResp.base_resp:type_name -> common.BaseResp
	1,  // 3: chat.SendMessageResp.message:type_name -> chat.ChatMessage
	10, // 4: chat.HistoryResp.base_resp:type_name -> common.BaseResp
	1,  // 5: chat.HistoryResp.messages:type_name -> chat.ChatMessage
	10, // 6: chat.GroupResp.base_resp:type_name -> common.BaseResp
	2,  // 7: chat.ChatService.SendMessage:input_type -> chat.SendMessageReq
	4,  // 8: chat.ChatService.GetMessageHistory:input_type -> chat.GetHistoryReq
	6,  // 9: chat.ChatService.MarkMessagesRead:input_type -> chat.MarkReadReq
	7,  // 10: chat.ChatService.CreateGroup:input_type -> chat.CreateGroupReq
	9,  // 11: chat.ChatService.JoinGroup:input_type -> chat.GroupMemberReq
	9,  // 12: chat.ChatService.LeaveGroup:input_type -> chat.GroupMemberReq
	3,  // 13: chat.ChatService.SendMessage:output_type -> chat.SendMessageResp
	5,  // 14: chat.ChatService.GetMessageHistory:output_type -> chat.HistoryResp
	10, // 15: chat.ChatService.MarkMessagesRead:output_type -> common.BaseResp
	8,  // 16: chat.ChatService.CreateGroup:output_type -> chat.GroupResp
	10, // 17: chat.ChatService.JoinGroup:output_type -> common.BaseResp
	10, // 18: chat.ChatService.LeaveGroup:output_type -> common.BaseResp
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_messaging_chat_proto_init() }
func file_messaging_chat_proto_init() {
	if File_messaging_chat_proto != nil {
		return
	}
	file_messaging_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_messaging_chat_proto_msgTypes[1].OneofWrappers = []any{}
	file_messaging_chat_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messaging_chat_proto_rawDesc), len(file_messaging_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messaging_chat_proto_goTypes,
		DependencyIndexes: file_messaging_chat_proto_depIdxs,
		EnumInfos:         file_messaging_chat_proto_enumTypes,
		MessageInfos:      file_messaging_chat_proto_msgTypes,
	}.Build()
	File_messaging_chat_proto = out.File
	file_messaging_chat_proto_goTypes = nil
	file_messaging_chat_proto_depIdxs = nil
}
