// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package search

import (
	"Noah/kitex_gen/common"
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type IndexType int64

const (
	IndexType_ENTITY   IndexType = 1
	IndexType_RELATION IndexType = 2
	IndexType_QUESTION IndexType = 3
	IndexType_ANSWER   IndexType = 4
	IndexType_DOCUMENT IndexType = 5
	IndexType_USER     IndexType = 6
)

func (p IndexType) String() string {
	switch p {
	case IndexType_ENTITY:
		return "ENTITY"
	case IndexType_RELATION:
		return "RELATION"
	case IndexType_QUESTION:
		return "QUESTION"
	case IndexType_ANSWER:
		return "ANSWER"
	case IndexType_DOCUMENT:
		return "DOCUMENT"
	case IndexType_USER:
		return "USER"
	}
	return "<UNSET>"
}

func IndexTypeFromString(s string) (IndexType, error) {
	switch s {
	case "ENTITY":
		return IndexType_ENTITY, nil
	case "RELATION":
		return IndexType_RELATION, nil
	case "QUESTION":
		return IndexType_QUESTION, nil
	case "ANSWER":
		return IndexType_ANSWER, nil
	case "DOCUMENT":
		return IndexType_DOCUMENT, nil
	case "USER":
		return IndexType_USER, nil
	}
	return IndexType(0), fmt.Errorf("not a valid IndexType string")
}

func IndexTypePtr(v IndexType) *IndexType { return &v }
func (p *IndexType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = IndexType(result.Int64)
	return
}

func (p *IndexType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SearchCondition struct {
	Field    string `thrift:"field,1" frugal:"1,default,string" json:"field"`
	Value    string `thrift:"value,2" frugal:"2,default,string" json:"value"`
	Operator string `thrift:"operator,3" frugal:"3,default,string" json:"operator"`
}

func NewSearchCondition() *SearchCondition {
	return &SearchCondition{}
}

func (p *SearchCondition) InitDefault() {
}

func (p *SearchCondition) GetField() (v string) {
	return p.Field
}

func (p *SearchCondition) GetValue() (v string) {
	return p.Value
}

func (p *SearchCondition) GetOperator() (v string) {
	return p.Operator
}
func (p *SearchCondition) SetField(val string) {
	p.Field = val
}
func (p *SearchCondition) SetValue(val string) {
	p.Value = val
}
func (p *SearchCondition) SetOperator(val string) {
	p.Operator = val
}

func (p *SearchCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchCondition(%+v)", *p)
}

var fieldIDToName_SearchCondition = map[int16]string{
	1: "field",
	2: "value",
	3: "operator",
}

type SortCondition struct {
	Field string `thrift:"field,1" frugal:"1,default,string" json:"field"`
	Order string `thrift:"order,2" frugal:"2,default,string" json:"order"`
}

func NewSortCondition() *SortCondition {
	return &SortCondition{}
}

func (p *SortCondition) InitDefault() {
}

func (p *SortCondition) GetField() (v string) {
	return p.Field
}

func (p *SortCondition) GetOrder() (v string) {
	return p.Order
}
func (p *SortCondition) SetField(val string) {
	p.Field = val
}
func (p *SortCondition) SetOrder(val string) {
	p.Order = val
}

func (p *SortCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortCondition(%+v)", *p)
}

var fieldIDToName_SortCondition = map[int16]string{
	1: "field",
	2: "order",
}

type SearchReq struct {
	Query      string             `thrift:"query,1" frugal:"1,default,string" json:"query"`
	IndexType  IndexType          `thrift:"indexType,2" frugal:"2,default,IndexType" json:"indexType"`
	Page       int32              `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize   int32              `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	Conditions []*SearchCondition `thrift:"conditions,5,optional" frugal:"5,optional,list<SearchCondition>" json:"conditions,omitempty"`
	Sorts      []*SortCondition   `thrift:"sorts,6,optional" frugal:"6,optional,list<SortCondition>" json:"sorts,omitempty"`
	Filters    map[string]string  `thrift:"filters,7,optional" frugal:"7,optional,map<string:string>" json:"filters,omitempty"`
}

func NewSearchReq() *SearchReq {
	return &SearchReq{}
}

func (p *SearchReq) InitDefault() {
}

func (p *SearchReq) GetQuery() (v string) {
	return p.Query
}

func (p *SearchReq) GetIndexType() (v IndexType) {
	return p.IndexType
}

func (p *SearchReq) GetPage() (v int32) {
	return p.Page
}

func (p *SearchReq) GetPageSize() (v int32) {
	return p.PageSize
}

var SearchReq_Conditions_DEFAULT []*SearchCondition

func (p *SearchReq) GetConditions() (v []*SearchCondition) {
	if !p.IsSetConditions() {
		return SearchReq_Conditions_DEFAULT
	}
	return p.Conditions
}

var SearchReq_Sorts_DEFAULT []*SortCondition

func (p *SearchReq) GetSorts() (v []*SortCondition) {
	if !p.IsSetSorts() {
		return SearchReq_Sorts_DEFAULT
	}
	return p.Sorts
}

var SearchReq_Filters_DEFAULT map[string]string

func (p *SearchReq) GetFilters() (v map[string]string) {
	if !p.IsSetFilters() {
		return SearchReq_Filters_DEFAULT
	}
	return p.Filters
}
func (p *SearchReq) SetQuery(val string) {
	p.Query = val
}
func (p *SearchReq) SetIndexType(val IndexType) {
	p.IndexType = val
}
func (p *SearchReq) SetPage(val int32) {
	p.Page = val
}
func (p *SearchReq) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *SearchReq) SetConditions(val []*SearchCondition) {
	p.Conditions = val
}
func (p *SearchReq) SetSorts(val []*SortCondition) {
	p.Sorts = val
}
func (p *SearchReq) SetFilters(val map[string]string) {
	p.Filters = val
}

func (p *SearchReq) IsSetConditions() bool {
	return p.Conditions != nil
}

func (p *SearchReq) IsSetSorts() bool {
	return p.Sorts != nil
}

func (p *SearchReq) IsSetFilters() bool {
	return p.Filters != nil
}

func (p *SearchReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchReq(%+v)", *p)
}

var fieldIDToName_SearchReq = map[int16]string{
	1: "query",
	2: "indexType",
	3: "page",
	4: "pageSize",
	5: "conditions",
	6: "sorts",
	7: "filters",
}

type SearchResultItem struct {
	Id       string            `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Type     string            `thrift:"type,2" frugal:"2,default,string" json:"type"`
	Title    string            `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Content  string            `thrift:"content,4" frugal:"4,default,string" json:"content"`
	Score    float64           `thrift:"score,5" frugal:"5,default,double" json:"score"`
	Metadata map[string]string `thrift:"metadata,6" frugal:"6,default,map<string:string>" json:"metadata"`
	Fields   map[string][]byte `thrift:"fields,7,optional" frugal:"7,optional,map<string:binary>" json:"fields,omitempty"`
}

func NewSearchResultItem() *SearchResultItem {
	return &SearchResultItem{}
}

func (p *SearchResultItem) InitDefault() {
}

func (p *SearchResultItem) GetId() (v string) {
	return p.Id
}

func (p *SearchResultItem) GetType() (v string) {
	return p.Type
}

func (p *SearchResultItem) GetTitle() (v string) {
	return p.Title
}

func (p *SearchResultItem) GetContent() (v string) {
	return p.Content
}

func (p *SearchResultItem) GetScore() (v float64) {
	return p.Score
}

func (p *SearchResultItem) GetMetadata() (v map[string]string) {
	return p.Metadata
}

var SearchResultItem_Fields_DEFAULT map[string][]byte

func (p *SearchResultItem) GetFields() (v map[string][]byte) {
	if !p.IsSetFields() {
		return SearchResultItem_Fields_DEFAULT
	}
	return p.Fields
}
func (p *SearchResultItem) SetId(val string) {
	p.Id = val
}
func (p *SearchResultItem) SetType(val string) {
	p.Type = val
}
func (p *SearchResultItem) SetTitle(val string) {
	p.Title = val
}
func (p *SearchResultItem) SetContent(val string) {
	p.Content = val
}
func (p *SearchResultItem) SetScore(val float64) {
	p.Score = val
}
func (p *SearchResultItem) SetMetadata(val map[string]string) {
	p.Metadata = val
}
func (p *SearchResultItem) SetFields(val map[string][]byte) {
	p.Fields = val
}

func (p *SearchResultItem) IsSetFields() bool {
	return p.Fields != nil
}

func (p *SearchResultItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchResultItem(%+v)", *p)
}

var fieldIDToName_SearchResultItem = map[int16]string{
	1: "id",
	2: "type",
	3: "title",
	4: "content",
	5: "score",
	6: "metadata",
	7: "fields",
}

type SearchResp struct {
	BaseResp   *common.BaseResp    `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Results    []*SearchResultItem `thrift:"results,2" frugal:"2,default,list<SearchResultItem>" json:"results"`
	Total      int64               `thrift:"total,3" frugal:"3,default,i64" json:"total"`
	SearchTime int64               `thrift:"searchTime,4" frugal:"4,default,i64" json:"searchTime"`
}

func NewSearchResp() *SearchResp {
	return &SearchResp{}
}

func (p *SearchResp) InitDefault() {
}

var SearchResp_BaseResp_DEFAULT *common.BaseResp

func (p *SearchResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return SearchResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *SearchResp) GetResults() (v []*SearchResultItem) {
	return p.Results
}

func (p *SearchResp) GetTotal() (v int64) {
	return p.Total
}

func (p *SearchResp) GetSearchTime() (v int64) {
	return p.SearchTime
}
func (p *SearchResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *SearchResp) SetResults(val []*SearchResultItem) {
	p.Results = val
}
func (p *SearchResp) SetTotal(val int64) {
	p.Total = val
}
func (p *SearchResp) SetSearchTime(val int64) {
	p.SearchTime = val
}

func (p *SearchResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SearchResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchResp(%+v)", *p)
}

var fieldIDToName_SearchResp = map[int16]string{
	1: "BaseResp",
	2: "results",
	3: "total",
	4: "searchTime",
}

type IndexDocument struct {
	Id        string            `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Type      IndexType         `thrift:"type,2" frugal:"2,default,IndexType" json:"type"`
	Title     string            `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Content   string            `thrift:"content,4" frugal:"4,default,string" json:"content"`
	Metadata  map[string]string `thrift:"metadata,5" frugal:"5,default,map<string:string>" json:"metadata"`
	CreatedAt int64             `thrift:"createdAt,6" frugal:"6,default,i64" json:"createdAt"`
	UpdatedAt int64             `thrift:"updatedAt,7" frugal:"7,default,i64" json:"updatedAt"`
	Fields    map[string][]byte `thrift:"fields,8,optional" frugal:"8,optional,map<string:binary>" json:"fields,omitempty"`
}

func NewIndexDocument() *IndexDocument {
	return &IndexDocument{}
}

func (p *IndexDocument) InitDefault() {
}

func (p *IndexDocument) GetId() (v string) {
	return p.Id
}

func (p *IndexDocument) GetType() (v IndexType) {
	return p.Type
}

func (p *IndexDocument) GetTitle() (v string) {
	return p.Title
}

func (p *IndexDocument) GetContent() (v string) {
	return p.Content
}

func (p *IndexDocument) GetMetadata() (v map[string]string) {
	return p.Metadata
}

func (p *IndexDocument) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *IndexDocument) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var IndexDocument_Fields_DEFAULT map[string][]byte

func (p *IndexDocument) GetFields() (v map[string][]byte) {
	if !p.IsSetFields() {
		return IndexDocument_Fields_DEFAULT
	}
	return p.Fields
}
func (p *IndexDocument) SetId(val string) {
	p.Id = val
}
func (p *IndexDocument) SetType(val IndexType) {
	p.Type = val
}
func (p *IndexDocument) SetTitle(val string) {
	p.Title = val
}
func (p *IndexDocument) SetContent(val string) {
	p.Content = val
}
func (p *IndexDocument) SetMetadata(val map[string]string) {
	p.Metadata = val
}
func (p *IndexDocument) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *IndexDocument) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *IndexDocument) SetFields(val map[string][]byte) {
	p.Fields = val
}

func (p *IndexDocument) IsSetFields() bool {
	return p.Fields != nil
}

func (p *IndexDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IndexDocument(%+v)", *p)
}

var fieldIDToName_IndexDocument = map[int16]string{
	1: "id",
	2: "type",
	3: "title",
	4: "content",
	5: "metadata",
	6: "createdAt",
	7: "updatedAt",
	8: "fields",
}

type AddDocumentReq struct {
	Type     IndexType         `thrift:"type,1" frugal:"1,default,IndexType" json:"type"`
	Title    string            `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Content  string            `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Metadata map[string]string `thrift:"metadata,4" frugal:"4,default,map<string:string>" json:"metadata"`
	Fields   map[string][]byte `thrift:"fields,5,optional" frugal:"5,optional,map<string:binary>" json:"fields,omitempty"`
}

func NewAddDocumentReq() *AddDocumentReq {
	return &AddDocumentReq{}
}

func (p *AddDocumentReq) InitDefault() {
}

func (p *AddDocumentReq) GetType() (v IndexType) {
	return p.Type
}

func (p *AddDocumentReq) GetTitle() (v string) {
	return p.Title
}

func (p *AddDocumentReq) GetContent() (v string) {
	return p.Content
}

func (p *AddDocumentReq) GetMetadata() (v map[string]string) {
	return p.Metadata
}

var AddDocumentReq_Fields_DEFAULT map[string][]byte

func (p *AddDocumentReq) GetFields() (v map[string][]byte) {
	if !p.IsSetFields() {
		return AddDocumentReq_Fields_DEFAULT
	}
	return p.Fields
}
func (p *AddDocumentReq) SetType(val IndexType) {
	p.Type = val
}
func (p *AddDocumentReq) SetTitle(val string) {
	p.Title = val
}
func (p *AddDocumentReq) SetContent(val string) {
	p.Content = val
}
func (p *AddDocumentReq) SetMetadata(val map[string]string) {
	p.Metadata = val
}
func (p *AddDocumentReq) SetFields(val map[string][]byte) {
	p.Fields = val
}

func (p *AddDocumentReq) IsSetFields() bool {
	return p.Fields != nil
}

func (p *AddDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddDocumentReq(%+v)", *p)
}

var fieldIDToName_AddDocumentReq = map[int16]string{
	1: "type",
	2: "title",
	3: "content",
	4: "metadata",
	5: "fields",
}

type UpdateDocumentReq struct {
	Id       string            `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Title    *string           `thrift:"title,2,optional" frugal:"2,optional,string" json:"title,omitempty"`
	Content  *string           `thrift:"content,3,optional" frugal:"3,optional,string" json:"content,omitempty"`
	Metadata map[string]string `thrift:"metadata,4,optional" frugal:"4,optional,map<string:string>" json:"metadata,omitempty"`
	Fields   map[string][]byte `thrift:"fields,5,optional" frugal:"5,optional,map<string:binary>" json:"fields,omitempty"`
}

func NewUpdateDocumentReq() *UpdateDocumentReq {
	return &UpdateDocumentReq{}
}

func (p *UpdateDocumentReq) InitDefault() {
}

func (p *UpdateDocumentReq) GetId() (v string) {
	return p.Id
}

var UpdateDocumentReq_Title_DEFAULT string

func (p *UpdateDocumentReq) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return UpdateDocumentReq_Title_DEFAULT
	}
	return *p.Title
}

var UpdateDocumentReq_Content_DEFAULT string

func (p *UpdateDocumentReq) GetContent() (v string) {
	if !p.IsSetContent() {
		return UpdateDocumentReq_Content_DEFAULT
	}
	return *p.Content
}

var UpdateDocumentReq_Metadata_DEFAULT map[string]string

func (p *UpdateDocumentReq) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return UpdateDocumentReq_Metadata_DEFAULT
	}
	return p.Metadata
}

var UpdateDocumentReq_Fields_DEFAULT map[string][]byte

func (p *UpdateDocumentReq) GetFields() (v map[string][]byte) {
	if !p.IsSetFields() {
		return UpdateDocumentReq_Fields_DEFAULT
	}
	return p.Fields
}
func (p *UpdateDocumentReq) SetId(val string) {
	p.Id = val
}
func (p *UpdateDocumentReq) SetTitle(val *string) {
	p.Title = val
}
func (p *UpdateDocumentReq) SetContent(val *string) {
	p.Content = val
}
func (p *UpdateDocumentReq) SetMetadata(val map[string]string) {
	p.Metadata = val
}
func (p *UpdateDocumentReq) SetFields(val map[string][]byte) {
	p.Fields = val
}

func (p *UpdateDocumentReq) IsSetTitle() bool {
	return p.Title != nil
}

func (p *UpdateDocumentReq) IsSetContent() bool {
	return p.Content != nil
}

func (p *UpdateDocumentReq) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *UpdateDocumentReq) IsSetFields() bool {
	return p.Fields != nil
}

func (p *UpdateDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateDocumentReq(%+v)", *p)
}

var fieldIDToName_UpdateDocumentReq = map[int16]string{
	1: "id",
	2: "title",
	3: "content",
	4: "metadata",
	5: "fields",
}

type DeleteDocumentReq struct {
	Id string `thrift:"id,1" frugal:"1,default,string" json:"id"`
}

func NewDeleteDocumentReq() *DeleteDocumentReq {
	return &DeleteDocumentReq{}
}

func (p *DeleteDocumentReq) InitDefault() {
}

func (p *DeleteDocumentReq) GetId() (v string) {
	return p.Id
}
func (p *DeleteDocumentReq) SetId(val string) {
	p.Id = val
}

func (p *DeleteDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteDocumentReq(%+v)", *p)
}

var fieldIDToName_DeleteDocumentReq = map[int16]string{
	1: "id",
}

type DocumentResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Document *IndexDocument   `thrift:"document,2" frugal:"2,default,IndexDocument" json:"document"`
}

func NewDocumentResp() *DocumentResp {
	return &DocumentResp{}
}

func (p *DocumentResp) InitDefault() {
}

var DocumentResp_BaseResp_DEFAULT *common.BaseResp

func (p *DocumentResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return DocumentResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var DocumentResp_Document_DEFAULT *IndexDocument

func (p *DocumentResp) GetDocument() (v *IndexDocument) {
	if !p.IsSetDocument() {
		return DocumentResp_Document_DEFAULT
	}
	return p.Document
}
func (p *DocumentResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *DocumentResp) SetDocument(val *IndexDocument) {
	p.Document = val
}

func (p *DocumentResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DocumentResp) IsSetDocument() bool {
	return p.Document != nil
}

func (p *DocumentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DocumentResp(%+v)", *p)
}

var fieldIDToName_DocumentResp = map[int16]string{
	1: "BaseResp",
	2: "document",
}

type BatchAddDocumentReq struct {
	Documents []*AddDocumentReq `thrift:"documents,1" frugal:"1,default,list<AddDocumentReq>" json:"documents"`
}

func NewBatchAddDocumentReq() *BatchAddDocumentReq {
	return &BatchAddDocumentReq{}
}

func (p *BatchAddDocumentReq) InitDefault() {
}

func (p *BatchAddDocumentReq) GetDocuments() (v []*AddDocumentReq) {
	return p.Documents
}
func (p *BatchAddDocumentReq) SetDocuments(val []*AddDocumentReq) {
	p.Documents = val
}

func (p *BatchAddDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchAddDocumentReq(%+v)", *p)
}

var fieldIDToName_BatchAddDocumentReq = map[int16]string{
	1: "documents",
}

type BatchDeleteDocumentReq struct {
	Ids []string `thrift:"ids,1" frugal:"1,default,list<string>" json:"ids"`
}

func NewBatchDeleteDocumentReq() *BatchDeleteDocumentReq {
	return &BatchDeleteDocumentReq{}
}

func (p *BatchDeleteDocumentReq) InitDefault() {
}

func (p *BatchDeleteDocumentReq) GetIds() (v []string) {
	return p.Ids
}
func (p *BatchDeleteDocumentReq) SetIds(val []string) {
	p.Ids = val
}

func (p *BatchDeleteDocumentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchDeleteDocumentReq(%+v)", *p)
}

var fieldIDToName_BatchDeleteDocumentReq = map[int16]string{
	1: "ids",
}

type IndexStats struct {
	Type          IndexType `thrift:"type,1" frugal:"1,default,IndexType" json:"type"`
	DocumentCount int64     `thrift:"documentCount,2" frugal:"2,default,i64" json:"documentCount"`
	SizeInBytes   int64     `thrift:"sizeInBytes,3" frugal:"3,default,i64" json:"sizeInBytes"`
	LastUpdated   string    `thrift:"lastUpdated,4" frugal:"4,default,string" json:"lastUpdated"`
}

func NewIndexStats() *IndexStats {
	return &IndexStats{}
}

func (p *IndexStats) InitDefault() {
}

func (p *IndexStats) GetType() (v IndexType) {
	return p.Type
}

func (p *IndexStats) GetDocumentCount() (v int64) {
	return p.DocumentCount
}

func (p *IndexStats) GetSizeInBytes() (v int64) {
	return p.SizeInBytes
}

func (p *IndexStats) GetLastUpdated() (v string) {
	return p.LastUpdated
}
func (p *IndexStats) SetType(val IndexType) {
	p.Type = val
}
func (p *IndexStats) SetDocumentCount(val int64) {
	p.DocumentCount = val
}
func (p *IndexStats) SetSizeInBytes(val int64) {
	p.SizeInBytes = val
}
func (p *IndexStats) SetLastUpdated(val string) {
	p.LastUpdated = val
}

func (p *IndexStats) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IndexStats(%+v)", *p)
}

var fieldIDToName_IndexStats = map[int16]string{
	1: "type",
	2: "documentCount",
	3: "sizeInBytes",
	4: "lastUpdated",
}

type IndexStatsResp struct {
	BaseResp *common.BaseResp `thrift:"BaseResp,1" frugal:"1,default,common.BaseResp" json:"BaseResp"`
	Stats    []*IndexStats    `thrift:"stats,2" frugal:"2,default,list<IndexStats>" json:"stats"`
}

func NewIndexStatsResp() *IndexStatsResp {
	return &IndexStatsResp{}
}

func (p *IndexStatsResp) InitDefault() {
}

var IndexStatsResp_BaseResp_DEFAULT *common.BaseResp

func (p *IndexStatsResp) GetBaseResp() (v *common.BaseResp) {
	if !p.IsSetBaseResp() {
		return IndexStatsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *IndexStatsResp) GetStats() (v []*IndexStats) {
	return p.Stats
}
func (p *IndexStatsResp) SetBaseResp(val *common.BaseResp) {
	p.BaseResp = val
}
func (p *IndexStatsResp) SetStats(val []*IndexStats) {
	p.Stats = val
}

func (p *IndexStatsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *IndexStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IndexStatsResp(%+v)", *p)
}

var fieldIDToName_IndexStatsResp = map[int16]string{
	1: "BaseResp",
	2: "stats",
}

type SearchService interface {
	Search(ctx context.Context, req *SearchReq) (r *SearchResp, err error)

	AddDocument(ctx context.Context, req *AddDocumentReq) (r *DocumentResp, err error)

	UpdateDocument(ctx context.Context, req *UpdateDocumentReq) (r *DocumentResp, err error)

	DeleteDocument(ctx context.Context, req *DeleteDocumentReq) (r *common.BaseResp, err error)

	GetDocument(ctx context.Context, id string) (r *DocumentResp, err error)

	BatchAddDocuments(ctx context.Context, req *BatchAddDocumentReq) (r *common.BaseResp, err error)

	BatchDeleteDocuments(ctx context.Context, req *BatchDeleteDocumentReq) (r *common.BaseResp, err error)

	CreateIndex(ctx context.Context, _type IndexType) (r *common.BaseResp, err error)

	DeleteIndex(ctx context.Context, _type IndexType) (r *common.BaseResp, err error)

	RefreshIndex(ctx context.Context, _type IndexType) (r *common.BaseResp, err error)

	GetIndexStats(ctx context.Context) (r *IndexStatsResp, err error)
}

type SearchServiceSearchArgs struct {
	Req *SearchReq `thrift:"req,1" frugal:"1,default,SearchReq" json:"req"`
}

func NewSearchServiceSearchArgs() *SearchServiceSearchArgs {
	return &SearchServiceSearchArgs{}
}

func (p *SearchServiceSearchArgs) InitDefault() {
}

var SearchServiceSearchArgs_Req_DEFAULT *SearchReq

func (p *SearchServiceSearchArgs) GetReq() (v *SearchReq) {
	if !p.IsSetReq() {
		return SearchServiceSearchArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceSearchArgs) SetReq(val *SearchReq) {
	p.Req = val
}

func (p *SearchServiceSearchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceSearchArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceSearchArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceSearchArgs = map[int16]string{
	1: "req",
}

type SearchServiceSearchResult struct {
	Success *SearchResp `thrift:"success,0,optional" frugal:"0,optional,SearchResp" json:"success,omitempty"`
}

func NewSearchServiceSearchResult() *SearchServiceSearchResult {
	return &SearchServiceSearchResult{}
}

func (p *SearchServiceSearchResult) InitDefault() {
}

var SearchServiceSearchResult_Success_DEFAULT *SearchResp

func (p *SearchServiceSearchResult) GetSuccess() (v *SearchResp) {
	if !p.IsSetSuccess() {
		return SearchServiceSearchResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceSearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*SearchResp)
}

func (p *SearchServiceSearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceSearchResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceSearchResult(%+v)", *p)
}

var fieldIDToName_SearchServiceSearchResult = map[int16]string{
	0: "success",
}

type SearchServiceAddDocumentArgs struct {
	Req *AddDocumentReq `thrift:"req,1" frugal:"1,default,AddDocumentReq" json:"req"`
}

func NewSearchServiceAddDocumentArgs() *SearchServiceAddDocumentArgs {
	return &SearchServiceAddDocumentArgs{}
}

func (p *SearchServiceAddDocumentArgs) InitDefault() {
}

var SearchServiceAddDocumentArgs_Req_DEFAULT *AddDocumentReq

func (p *SearchServiceAddDocumentArgs) GetReq() (v *AddDocumentReq) {
	if !p.IsSetReq() {
		return SearchServiceAddDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceAddDocumentArgs) SetReq(val *AddDocumentReq) {
	p.Req = val
}

func (p *SearchServiceAddDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceAddDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceAddDocumentArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceAddDocumentArgs = map[int16]string{
	1: "req",
}

type SearchServiceAddDocumentResult struct {
	Success *DocumentResp `thrift:"success,0,optional" frugal:"0,optional,DocumentResp" json:"success,omitempty"`
}

func NewSearchServiceAddDocumentResult() *SearchServiceAddDocumentResult {
	return &SearchServiceAddDocumentResult{}
}

func (p *SearchServiceAddDocumentResult) InitDefault() {
}

var SearchServiceAddDocumentResult_Success_DEFAULT *DocumentResp

func (p *SearchServiceAddDocumentResult) GetSuccess() (v *DocumentResp) {
	if !p.IsSetSuccess() {
		return SearchServiceAddDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceAddDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*DocumentResp)
}

func (p *SearchServiceAddDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceAddDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceAddDocumentResult(%+v)", *p)
}

var fieldIDToName_SearchServiceAddDocumentResult = map[int16]string{
	0: "success",
}

type SearchServiceUpdateDocumentArgs struct {
	Req *UpdateDocumentReq `thrift:"req,1" frugal:"1,default,UpdateDocumentReq" json:"req"`
}

func NewSearchServiceUpdateDocumentArgs() *SearchServiceUpdateDocumentArgs {
	return &SearchServiceUpdateDocumentArgs{}
}

func (p *SearchServiceUpdateDocumentArgs) InitDefault() {
}

var SearchServiceUpdateDocumentArgs_Req_DEFAULT *UpdateDocumentReq

func (p *SearchServiceUpdateDocumentArgs) GetReq() (v *UpdateDocumentReq) {
	if !p.IsSetReq() {
		return SearchServiceUpdateDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceUpdateDocumentArgs) SetReq(val *UpdateDocumentReq) {
	p.Req = val
}

func (p *SearchServiceUpdateDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceUpdateDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceUpdateDocumentArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceUpdateDocumentArgs = map[int16]string{
	1: "req",
}

type SearchServiceUpdateDocumentResult struct {
	Success *DocumentResp `thrift:"success,0,optional" frugal:"0,optional,DocumentResp" json:"success,omitempty"`
}

func NewSearchServiceUpdateDocumentResult() *SearchServiceUpdateDocumentResult {
	return &SearchServiceUpdateDocumentResult{}
}

func (p *SearchServiceUpdateDocumentResult) InitDefault() {
}

var SearchServiceUpdateDocumentResult_Success_DEFAULT *DocumentResp

func (p *SearchServiceUpdateDocumentResult) GetSuccess() (v *DocumentResp) {
	if !p.IsSetSuccess() {
		return SearchServiceUpdateDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceUpdateDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*DocumentResp)
}

func (p *SearchServiceUpdateDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceUpdateDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceUpdateDocumentResult(%+v)", *p)
}

var fieldIDToName_SearchServiceUpdateDocumentResult = map[int16]string{
	0: "success",
}

type SearchServiceDeleteDocumentArgs struct {
	Req *DeleteDocumentReq `thrift:"req,1" frugal:"1,default,DeleteDocumentReq" json:"req"`
}

func NewSearchServiceDeleteDocumentArgs() *SearchServiceDeleteDocumentArgs {
	return &SearchServiceDeleteDocumentArgs{}
}

func (p *SearchServiceDeleteDocumentArgs) InitDefault() {
}

var SearchServiceDeleteDocumentArgs_Req_DEFAULT *DeleteDocumentReq

func (p *SearchServiceDeleteDocumentArgs) GetReq() (v *DeleteDocumentReq) {
	if !p.IsSetReq() {
		return SearchServiceDeleteDocumentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceDeleteDocumentArgs) SetReq(val *DeleteDocumentReq) {
	p.Req = val
}

func (p *SearchServiceDeleteDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceDeleteDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceDeleteDocumentArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceDeleteDocumentArgs = map[int16]string{
	1: "req",
}

type SearchServiceDeleteDocumentResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceDeleteDocumentResult() *SearchServiceDeleteDocumentResult {
	return &SearchServiceDeleteDocumentResult{}
}

func (p *SearchServiceDeleteDocumentResult) InitDefault() {
}

var SearchServiceDeleteDocumentResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceDeleteDocumentResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceDeleteDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceDeleteDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceDeleteDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceDeleteDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceDeleteDocumentResult(%+v)", *p)
}

var fieldIDToName_SearchServiceDeleteDocumentResult = map[int16]string{
	0: "success",
}

type SearchServiceGetDocumentArgs struct {
	Id string `thrift:"id,1" frugal:"1,default,string" json:"id"`
}

func NewSearchServiceGetDocumentArgs() *SearchServiceGetDocumentArgs {
	return &SearchServiceGetDocumentArgs{}
}

func (p *SearchServiceGetDocumentArgs) InitDefault() {
}

func (p *SearchServiceGetDocumentArgs) GetId() (v string) {
	return p.Id
}
func (p *SearchServiceGetDocumentArgs) SetId(val string) {
	p.Id = val
}

func (p *SearchServiceGetDocumentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceGetDocumentArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceGetDocumentArgs = map[int16]string{
	1: "id",
}

type SearchServiceGetDocumentResult struct {
	Success *DocumentResp `thrift:"success,0,optional" frugal:"0,optional,DocumentResp" json:"success,omitempty"`
}

func NewSearchServiceGetDocumentResult() *SearchServiceGetDocumentResult {
	return &SearchServiceGetDocumentResult{}
}

func (p *SearchServiceGetDocumentResult) InitDefault() {
}

var SearchServiceGetDocumentResult_Success_DEFAULT *DocumentResp

func (p *SearchServiceGetDocumentResult) GetSuccess() (v *DocumentResp) {
	if !p.IsSetSuccess() {
		return SearchServiceGetDocumentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceGetDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*DocumentResp)
}

func (p *SearchServiceGetDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceGetDocumentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceGetDocumentResult(%+v)", *p)
}

var fieldIDToName_SearchServiceGetDocumentResult = map[int16]string{
	0: "success",
}

type SearchServiceBatchAddDocumentsArgs struct {
	Req *BatchAddDocumentReq `thrift:"req,1" frugal:"1,default,BatchAddDocumentReq" json:"req"`
}

func NewSearchServiceBatchAddDocumentsArgs() *SearchServiceBatchAddDocumentsArgs {
	return &SearchServiceBatchAddDocumentsArgs{}
}

func (p *SearchServiceBatchAddDocumentsArgs) InitDefault() {
}

var SearchServiceBatchAddDocumentsArgs_Req_DEFAULT *BatchAddDocumentReq

func (p *SearchServiceBatchAddDocumentsArgs) GetReq() (v *BatchAddDocumentReq) {
	if !p.IsSetReq() {
		return SearchServiceBatchAddDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceBatchAddDocumentsArgs) SetReq(val *BatchAddDocumentReq) {
	p.Req = val
}

func (p *SearchServiceBatchAddDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceBatchAddDocumentsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceBatchAddDocumentsArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceBatchAddDocumentsArgs = map[int16]string{
	1: "req",
}

type SearchServiceBatchAddDocumentsResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceBatchAddDocumentsResult() *SearchServiceBatchAddDocumentsResult {
	return &SearchServiceBatchAddDocumentsResult{}
}

func (p *SearchServiceBatchAddDocumentsResult) InitDefault() {
}

var SearchServiceBatchAddDocumentsResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceBatchAddDocumentsResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceBatchAddDocumentsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceBatchAddDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceBatchAddDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceBatchAddDocumentsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceBatchAddDocumentsResult(%+v)", *p)
}

var fieldIDToName_SearchServiceBatchAddDocumentsResult = map[int16]string{
	0: "success",
}

type SearchServiceBatchDeleteDocumentsArgs struct {
	Req *BatchDeleteDocumentReq `thrift:"req,1" frugal:"1,default,BatchDeleteDocumentReq" json:"req"`
}

func NewSearchServiceBatchDeleteDocumentsArgs() *SearchServiceBatchDeleteDocumentsArgs {
	return &SearchServiceBatchDeleteDocumentsArgs{}
}

func (p *SearchServiceBatchDeleteDocumentsArgs) InitDefault() {
}

var SearchServiceBatchDeleteDocumentsArgs_Req_DEFAULT *BatchDeleteDocumentReq

func (p *SearchServiceBatchDeleteDocumentsArgs) GetReq() (v *BatchDeleteDocumentReq) {
	if !p.IsSetReq() {
		return SearchServiceBatchDeleteDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SearchServiceBatchDeleteDocumentsArgs) SetReq(val *BatchDeleteDocumentReq) {
	p.Req = val
}

func (p *SearchServiceBatchDeleteDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchServiceBatchDeleteDocumentsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceBatchDeleteDocumentsArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceBatchDeleteDocumentsArgs = map[int16]string{
	1: "req",
}

type SearchServiceBatchDeleteDocumentsResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceBatchDeleteDocumentsResult() *SearchServiceBatchDeleteDocumentsResult {
	return &SearchServiceBatchDeleteDocumentsResult{}
}

func (p *SearchServiceBatchDeleteDocumentsResult) InitDefault() {
}

var SearchServiceBatchDeleteDocumentsResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceBatchDeleteDocumentsResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceBatchDeleteDocumentsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceBatchDeleteDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceBatchDeleteDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceBatchDeleteDocumentsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceBatchDeleteDocumentsResult(%+v)", *p)
}

var fieldIDToName_SearchServiceBatchDeleteDocumentsResult = map[int16]string{
	0: "success",
}

type SearchServiceCreateIndexArgs struct {
	Type IndexType `thrift:"type,1" frugal:"1,default,IndexType" json:"type"`
}

func NewSearchServiceCreateIndexArgs() *SearchServiceCreateIndexArgs {
	return &SearchServiceCreateIndexArgs{}
}

func (p *SearchServiceCreateIndexArgs) InitDefault() {
}

func (p *SearchServiceCreateIndexArgs) GetType() (v IndexType) {
	return p.Type
}
func (p *SearchServiceCreateIndexArgs) SetType(val IndexType) {
	p.Type = val
}

func (p *SearchServiceCreateIndexArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceCreateIndexArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceCreateIndexArgs = map[int16]string{
	1: "type",
}

type SearchServiceCreateIndexResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceCreateIndexResult() *SearchServiceCreateIndexResult {
	return &SearchServiceCreateIndexResult{}
}

func (p *SearchServiceCreateIndexResult) InitDefault() {
}

var SearchServiceCreateIndexResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceCreateIndexResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceCreateIndexResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceCreateIndexResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceCreateIndexResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceCreateIndexResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceCreateIndexResult(%+v)", *p)
}

var fieldIDToName_SearchServiceCreateIndexResult = map[int16]string{
	0: "success",
}

type SearchServiceDeleteIndexArgs struct {
	Type IndexType `thrift:"type,1" frugal:"1,default,IndexType" json:"type"`
}

func NewSearchServiceDeleteIndexArgs() *SearchServiceDeleteIndexArgs {
	return &SearchServiceDeleteIndexArgs{}
}

func (p *SearchServiceDeleteIndexArgs) InitDefault() {
}

func (p *SearchServiceDeleteIndexArgs) GetType() (v IndexType) {
	return p.Type
}
func (p *SearchServiceDeleteIndexArgs) SetType(val IndexType) {
	p.Type = val
}

func (p *SearchServiceDeleteIndexArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceDeleteIndexArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceDeleteIndexArgs = map[int16]string{
	1: "type",
}

type SearchServiceDeleteIndexResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceDeleteIndexResult() *SearchServiceDeleteIndexResult {
	return &SearchServiceDeleteIndexResult{}
}

func (p *SearchServiceDeleteIndexResult) InitDefault() {
}

var SearchServiceDeleteIndexResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceDeleteIndexResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceDeleteIndexResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceDeleteIndexResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceDeleteIndexResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceDeleteIndexResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceDeleteIndexResult(%+v)", *p)
}

var fieldIDToName_SearchServiceDeleteIndexResult = map[int16]string{
	0: "success",
}

type SearchServiceRefreshIndexArgs struct {
	Type IndexType `thrift:"type,1" frugal:"1,default,IndexType" json:"type"`
}

func NewSearchServiceRefreshIndexArgs() *SearchServiceRefreshIndexArgs {
	return &SearchServiceRefreshIndexArgs{}
}

func (p *SearchServiceRefreshIndexArgs) InitDefault() {
}

func (p *SearchServiceRefreshIndexArgs) GetType() (v IndexType) {
	return p.Type
}
func (p *SearchServiceRefreshIndexArgs) SetType(val IndexType) {
	p.Type = val
}

func (p *SearchServiceRefreshIndexArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceRefreshIndexArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceRefreshIndexArgs = map[int16]string{
	1: "type",
}

type SearchServiceRefreshIndexResult struct {
	Success *common.BaseResp `thrift:"success,0,optional" frugal:"0,optional,common.BaseResp" json:"success,omitempty"`
}

func NewSearchServiceRefreshIndexResult() *SearchServiceRefreshIndexResult {
	return &SearchServiceRefreshIndexResult{}
}

func (p *SearchServiceRefreshIndexResult) InitDefault() {
}

var SearchServiceRefreshIndexResult_Success_DEFAULT *common.BaseResp

func (p *SearchServiceRefreshIndexResult) GetSuccess() (v *common.BaseResp) {
	if !p.IsSetSuccess() {
		return SearchServiceRefreshIndexResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceRefreshIndexResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResp)
}

func (p *SearchServiceRefreshIndexResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceRefreshIndexResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceRefreshIndexResult(%+v)", *p)
}

var fieldIDToName_SearchServiceRefreshIndexResult = map[int16]string{
	0: "success",
}

type SearchServiceGetIndexStatsArgs struct {
}

func NewSearchServiceGetIndexStatsArgs() *SearchServiceGetIndexStatsArgs {
	return &SearchServiceGetIndexStatsArgs{}
}

func (p *SearchServiceGetIndexStatsArgs) InitDefault() {
}

func (p *SearchServiceGetIndexStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceGetIndexStatsArgs(%+v)", *p)
}

var fieldIDToName_SearchServiceGetIndexStatsArgs = map[int16]string{}

type SearchServiceGetIndexStatsResult struct {
	Success *IndexStatsResp `thrift:"success,0,optional" frugal:"0,optional,IndexStatsResp" json:"success,omitempty"`
}

func NewSearchServiceGetIndexStatsResult() *SearchServiceGetIndexStatsResult {
	return &SearchServiceGetIndexStatsResult{}
}

func (p *SearchServiceGetIndexStatsResult) InitDefault() {
}

var SearchServiceGetIndexStatsResult_Success_DEFAULT *IndexStatsResp

func (p *SearchServiceGetIndexStatsResult) GetSuccess() (v *IndexStatsResp) {
	if !p.IsSetSuccess() {
		return SearchServiceGetIndexStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SearchServiceGetIndexStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*IndexStatsResp)
}

func (p *SearchServiceGetIndexStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchServiceGetIndexStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchServiceGetIndexStatsResult(%+v)", *p)
}

var fieldIDToName_SearchServiceGetIndexStatsResult = map[int16]string{
	0: "success",
}
