// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: messaging/contact.proto

package contact

import (
	common "Logos/proto_gen/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContactService_AddFriend_FullMethodName           = "/contact.ContactService/AddFriend"
	ContactService_HandleFriendRequest_FullMethodName = "/contact.ContactService/HandleFriendRequest"
	ContactService_RemoveFriend_FullMethodName        = "/contact.ContactService/RemoveFriend"
	ContactService_GetFriendList_FullMethodName       = "/contact.ContactService/GetFriendList"
	ContactService_GetPendingRequests_FullMethodName  = "/contact.ContactService/GetPendingRequests"
	ContactService_BlockUser_FullMethodName           = "/contact.ContactService/BlockUser"
	ContactService_UnblockUser_FullMethodName         = "/contact.ContactService/UnblockUser"
)

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContactServiceClient interface {
	AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error)
	HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*common.BaseResp, error)
	RemoveFriend(ctx context.Context, in *RemoveFriendReq, opts ...grpc.CallOption) (*common.BaseResp, error)
	GetFriendList(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*FriendListResp, error)
	GetPendingRequests(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*FriendListResp, error)
	BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResp, error)
	UnblockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResp, error)
}

type contactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContactServiceClient(cc grpc.ClientConnInterface) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFriendResp)
	err := c.cc.Invoke(ctx, ContactService_AddFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*common.BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResp)
	err := c.cc.Invoke(ctx, ContactService_HandleFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) RemoveFriend(ctx context.Context, in *RemoveFriendReq, opts ...grpc.CallOption) (*common.BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResp)
	err := c.cc.Invoke(ctx, ContactService_RemoveFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetFriendList(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendListResp)
	err := c.cc.Invoke(ctx, ContactService_GetFriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetPendingRequests(ctx context.Context, in *GetByUserIdReq, opts ...grpc.CallOption) (*FriendListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendListResp)
	err := c.cc.Invoke(ctx, ContactService_GetPendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResp)
	err := c.cc.Invoke(ctx, ContactService_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) UnblockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*common.BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BaseResp)
	err := c.cc.Invoke(ctx, ContactService_UnblockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
// All implementations must embed UnimplementedContactServiceServer
// for forward compatibility.
type ContactServiceServer interface {
	AddFriend(context.Context, *AddFriendReq) (*AddFriendResp, error)
	HandleFriendRequest(context.Context, *HandleFriendReq) (*common.BaseResp, error)
	RemoveFriend(context.Context, *RemoveFriendReq) (*common.BaseResp, error)
	GetFriendList(context.Context, *GetByUserIdReq) (*FriendListResp, error)
	GetPendingRequests(context.Context, *GetByUserIdReq) (*FriendListResp, error)
	BlockUser(context.Context, *BlockUserReq) (*common.BaseResp, error)
	UnblockUser(context.Context, *BlockUserReq) (*common.BaseResp, error)
	mustEmbedUnimplementedContactServiceServer()
}

// UnimplementedContactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContactServiceServer struct{}

func (UnimplementedContactServiceServer) AddFriend(context.Context, *AddFriendReq) (*AddFriendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFriend not implemented")
}
func (UnimplementedContactServiceServer) HandleFriendRequest(context.Context, *HandleFriendReq) (*common.BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFriendRequest not implemented")
}
func (UnimplementedContactServiceServer) RemoveFriend(context.Context, *RemoveFriendReq) (*common.BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedContactServiceServer) GetFriendList(context.Context, *GetByUserIdReq) (*FriendListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedContactServiceServer) GetPendingRequests(context.Context, *GetByUserIdReq) (*FriendListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingRequests not implemented")
}
func (UnimplementedContactServiceServer) BlockUser(context.Context, *BlockUserReq) (*common.BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedContactServiceServer) UnblockUser(context.Context, *BlockUserReq) (*common.BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockUser not implemented")
}
func (UnimplementedContactServiceServer) mustEmbedUnimplementedContactServiceServer() {}
func (UnimplementedContactServiceServer) testEmbeddedByValue()                        {}

// UnsafeContactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContactServiceServer will
// result in compilation errors.
type UnsafeContactServiceServer interface {
	mustEmbedUnimplementedContactServiceServer()
}

func RegisterContactServiceServer(s grpc.ServiceRegistrar, srv ContactServiceServer) {
	// If the following call panics, it indicates UnimplementedContactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContactService_ServiceDesc, srv)
}

func _ContactService_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_AddFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).AddFriend(ctx, req.(*AddFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_HandleFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).HandleFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_HandleFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).HandleFriendRequest(ctx, req.(*HandleFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).RemoveFriend(ctx, req.(*RemoveFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetFriendList(ctx, req.(*GetByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetPendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetPendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_GetPendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetPendingRequests(ctx, req.(*GetByUserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).BlockUser(ctx, req.(*BlockUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_UnblockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).UnblockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactService_UnblockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).UnblockUser(ctx, req.(*BlockUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ContactService_ServiceDesc is the grpc.ServiceDesc for ContactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contact.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFriend",
			Handler:    _ContactService_AddFriend_Handler,
		},
		{
			MethodName: "HandleFriendRequest",
			Handler:    _ContactService_HandleFriendRequest_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _ContactService_RemoveFriend_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _ContactService_GetFriendList_Handler,
		},
		{
			MethodName: "GetPendingRequests",
			Handler:    _ContactService_GetPendingRequests_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _ContactService_BlockUser_Handler,
		},
		{
			MethodName: "UnblockUser",
			Handler:    _ContactService_UnblockUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messaging/contact.proto",
}
