// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ai/knowledge.proto

package knowledge

import (
	common "Logos/proto_gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_ai_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Entity) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Entity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Entity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_ai_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *Relation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Relation) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Relation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Relation) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Relation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Relation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Relation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddEntityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityReq) Reset() {
	*x = AddEntityReq{}
	mi := &file_ai_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityReq) ProtoMessage() {}

func (x *AddEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityReq.ProtoReflect.Descriptor instead.
func (*AddEntityReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *AddEntityReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddEntityReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddEntityReq) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *AddEntityReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateEntityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityReq) Reset() {
	*x = UpdateEntityReq{}
	mi := &file_ai_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityReq) ProtoMessage() {}

func (x *UpdateEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityReq.ProtoReflect.Descriptor instead.
func (*UpdateEntityReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEntityReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEntityReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateEntityReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEntityReq) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *UpdateEntityReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteEntityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntityReq) Reset() {
	*x = DeleteEntityReq{}
	mi := &file_ai_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntityReq) ProtoMessage() {}

func (x *DeleteEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntityReq.ProtoReflect.Descriptor instead.
func (*DeleteEntityReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEntityReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EntityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Entity        *Entity                `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResp) Reset() {
	*x = EntityResp{}
	mi := &file_ai_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResp) ProtoMessage() {}

func (x *EntityResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResp.ProtoReflect.Descriptor instead.
func (*EntityResp) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *EntityResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *EntityResp) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type BatchEntityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEntityResp) Reset() {
	*x = BatchEntityResp{}
	mi := &file_ai_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEntityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEntityResp) ProtoMessage() {}

func (x *BatchEntityResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEntityResp.ProtoReflect.Descriptor instead.
func (*BatchEntityResp) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *BatchEntityResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *BatchEntityResp) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type AddRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRelationReq) Reset() {
	*x = AddRelationReq{}
	mi := &file_ai_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRelationReq) ProtoMessage() {}

func (x *AddRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRelationReq.ProtoReflect.Descriptor instead.
func (*AddRelationReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *AddRelationReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddRelationReq) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AddRelationReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AddRelationReq) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *AddRelationReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	SourceId      *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	TargetId      *string                `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRelationReq) Reset() {
	*x = UpdateRelationReq{}
	mi := &file_ai_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRelationReq) ProtoMessage() {}

func (x *UpdateRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRelationReq.ProtoReflect.Descriptor instead.
func (*UpdateRelationReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRelationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRelationReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateRelationReq) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *UpdateRelationReq) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *UpdateRelationReq) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *UpdateRelationReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationReq) Reset() {
	*x = DeleteRelationReq{}
	mi := &file_ai_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationReq) ProtoMessage() {}

func (x *DeleteRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationReq.ProtoReflect.Descriptor instead.
func (*DeleteRelationReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRelationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RelationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Relation      *Relation              `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationResp) Reset() {
	*x = RelationResp{}
	mi := &file_ai_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationResp) ProtoMessage() {}

func (x *RelationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationResp.ProtoReflect.Descriptor instead.
func (*RelationResp) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *RelationResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *RelationResp) GetRelation() *Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type BatchRelationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Relations     []*Relation            `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRelationResp) Reset() {
	*x = BatchRelationResp{}
	mi := &file_ai_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRelationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRelationResp) ProtoMessage() {}

func (x *BatchRelationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRelationResp.ProtoReflect.Descriptor instead.
func (*BatchRelationResp) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *BatchRelationResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *BatchRelationResp) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type QueryEntityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEntityReq) Reset() {
	*x = QueryEntityReq{}
	mi := &file_ai_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEntityReq) ProtoMessage() {}

func (x *QueryEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEntityReq.ProtoReflect.Descriptor instead.
func (*QueryEntityReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *QueryEntityReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *QueryEntityReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QueryEntityReq) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *QueryEntityReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryEntityReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type QueryRelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	SourceId      *string                `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	TargetId      *string                `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRelationReq) Reset() {
	*x = QueryRelationReq{}
	mi := &file_ai_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRelationReq) ProtoMessage() {}

func (x *QueryRelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRelationReq.ProtoReflect.Descriptor instead.
func (*QueryRelationReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *QueryRelationReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *QueryRelationReq) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *QueryRelationReq) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *QueryRelationReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryRelationReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GraphStatsResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseResp          *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	EntityCount       int64                  `protobuf:"varint,2,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	RelationCount     int64                  `protobuf:"varint,3,opt,name=relation_count,json=relationCount,proto3" json:"relation_count,omitempty"`
	EntityTypeCount   map[string]int64       `protobuf:"bytes,4,rep,name=entity_type_count,json=entityTypeCount,proto3" json:"entity_type_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RelationTypeCount map[string]int64       `protobuf:"bytes,5,rep,name=relation_type_count,json=relationTypeCount,proto3" json:"relation_type_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GraphStatsResp) Reset() {
	*x = GraphStatsResp{}
	mi := &file_ai_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStatsResp) ProtoMessage() {}

func (x *GraphStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStatsResp.ProtoReflect.Descriptor instead.
func (*GraphStatsResp) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *GraphStatsResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *GraphStatsResp) GetEntityCount() int64 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *GraphStatsResp) GetRelationCount() int64 {
	if x != nil {
		return x.RelationCount
	}
	return 0
}

func (x *GraphStatsResp) GetEntityTypeCount() map[string]int64 {
	if x != nil {
		return x.EntityTypeCount
	}
	return nil
}

func (x *GraphStatsResp) GetRelationTypeCount() map[string]int64 {
	if x != nil {
		return x.RelationTypeCount
	}
	return nil
}

type ImportDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      string                 `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Data          []string               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDataReq) Reset() {
	*x = ImportDataReq{}
	mi := &file_ai_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDataReq) ProtoMessage() {}

func (x *ImportDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDataReq.ProtoReflect.Descriptor instead.
func (*ImportDataReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *ImportDataReq) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ImportDataReq) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchEntityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntityReq) Reset() {
	*x = SearchEntityReq{}
	mi := &file_ai_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntityReq) ProtoMessage() {}

func (x *SearchEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntityReq.ProtoReflect.Descriptor instead.
func (*SearchEntityReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *SearchEntityReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchEntityReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *SearchEntityReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchEntityReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_ai_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *GetByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRelatedEntitiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	RelationType  *string                `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3,oneof" json:"relation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedEntitiesReq) Reset() {
	*x = GetRelatedEntitiesReq{}
	mi := &file_ai_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedEntitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedEntitiesReq) ProtoMessage() {}

func (x *GetRelatedEntitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedEntitiesReq.ProtoReflect.Descriptor instead.
func (*GetRelatedEntitiesReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *GetRelatedEntitiesReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetRelatedEntitiesReq) GetRelationType() string {
	if x != nil && x.RelationType != nil {
		return *x.RelationType
	}
	return ""
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_ai_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_ai_knowledge_proto_rawDescGZIP(), []int{19}
}

var File_ai_knowledge_proto protoreflect.FileDescriptor

const file_ai_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x12ai/knowledge.proto\x12\tknowledge\x1a\fcommon.proto\"\xb7\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12A\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2!.knowledge.Entity.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\xe1\x02\n" +
	"\bRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12C\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2#.knowledge.Relation.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\xf5\x01\n" +
	"\fAddEntityReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2'.knowledge.AddEntityReq.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\xa7\x02\n" +
	"\x0fUpdateEntityReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12J\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2*.knowledge.UpdateEntityReq.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_typeB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"!\n" +
	"\x0fDeleteEntityReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\n" +
	"EntityResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12)\n" +
	"\x06entity\x18\x02 \x01(\v2\x11.knowledge.EntityR\x06entity\"o\n" +
	"\x0fBatchEntityResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12-\n" +
	"\bentities\x18\x02 \x03(\v2\x11.knowledge.EntityR\bentities\"\x9f\x02\n" +
	"\x0eAddRelationReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12I\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2).knowledge.AddRelationReq.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\xe9\x02\n" +
	"\x11UpdateRelationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x01R\bsourceId\x88\x01\x01\x12 \n" +
	"\ttarget_id\x18\x04 \x01(\tH\x02R\btargetId\x88\x01\x01\x12L\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2,.knowledge.UpdateRelationReq.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x03R\vdescription\x88\x01\x01\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_source_idB\f\n" +
	"\n" +
	"_target_idB\x0e\n" +
	"\f_description\"#\n" +
	"\x11DeleteRelationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\fRelationResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12/\n" +
	"\brelation\x18\x02 \x01(\v2\x13.knowledge.RelationR\brelation\"u\n" +
	"\x11BatchRelationResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x121\n" +
	"\trelations\x18\x02 \x03(\v2\x13.knowledge.RelationR\trelations\"\x8f\x02\n" +
	"\x0eQueryEntityReq\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12I\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2).knowledge.QueryEntityReq.PropertiesEntryR\n" +
	"properties\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_typeB\a\n" +
	"\x05_name\"\xc5\x01\n" +
	"\x10QueryRelationReq\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x02 \x01(\tH\x01R\bsourceId\x88\x01\x01\x12 \n" +
	"\ttarget_id\x18\x03 \x01(\tH\x02R\btargetId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSizeB\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_source_idB\f\n" +
	"\n" +
	"_target_id\"\xd1\x03\n" +
	"\x0eGraphStatsResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12!\n" +
	"\fentity_count\x18\x02 \x01(\x03R\ventityCount\x12%\n" +
	"\x0erelation_count\x18\x03 \x01(\x03R\rrelationCount\x12Z\n" +
	"\x11entity_type_count\x18\x04 \x03(\v2..knowledge.GraphStatsResp.EntityTypeCountEntryR\x0fentityTypeCount\x12`\n" +
	"\x13relation_type_count\x18\x05 \x03(\v20.knowledge.GraphStatsResp.RelationTypeCountEntryR\x11relationTypeCount\x1aB\n" +
	"\x14EntityTypeCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aD\n" +
	"\x16RelationTypeCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"@\n" +
	"\rImportDataReq\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\tR\bdataType\x12\x12\n" +
	"\x04data\x18\x02 \x03(\tR\x04data\"~\n" +
	"\x0fSearchEntityReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\a\n" +
	"\x05_type\"\x1c\n" +
	"\n" +
	"GetByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\x15GetRelatedEntitiesReq\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12(\n" +
	"\rrelation_type\x18\x02 \x01(\tH\x00R\frelationType\x88\x01\x01B\x10\n" +
	"\x0e_relation_type\"\n" +
	"\n" +
	"\bEmptyReq2\xc6\a\n" +
	"\x10KnowledgeService\x12;\n" +
	"\tAddEntity\x12\x17.knowledge.AddEntityReq\x1a\x15.knowledge.EntityResp\x12A\n" +
	"\fUpdateEntity\x12\x1a.knowledge.UpdateEntityReq\x1a\x15.knowledge.EntityResp\x12<\n" +
	"\fDeleteEntity\x12\x1a.knowledge.DeleteEntityReq\x1a\x10.common.BaseResp\x129\n" +
	"\tGetEntity\x12\x15.knowledge.GetByIdReq\x1a\x15.knowledge.EntityResp\x12F\n" +
	"\rQueryEntities\x12\x19.knowledge.QueryEntityReq\x1a\x1a.knowledge.BatchEntityResp\x12H\n" +
	"\x0eSearchEntities\x12\x1a.knowledge.SearchEntityReq\x1a\x1a.knowledge.BatchEntityResp\x12A\n" +
	"\vAddRelation\x12\x19.knowledge.AddRelationReq\x1a\x17.knowledge.RelationResp\x12G\n" +
	"\x0eUpdateRelation\x12\x1c.knowledge.UpdateRelationReq\x1a\x17.knowledge.RelationResp\x12@\n" +
	"\x0eDeleteRelation\x12\x1c.knowledge.DeleteRelationReq\x1a\x10.common.BaseResp\x12=\n" +
	"\vGetRelation\x12\x15.knowledge.GetByIdReq\x1a\x17.knowledge.RelationResp\x12K\n" +
	"\x0eQueryRelations\x12\x1b.knowledge.QueryRelationReq\x1a\x1c.knowledge.BatchRelationResp\x12?\n" +
	"\rGetGraphStats\x12\x13.knowledge.EmptyReq\x1a\x19.knowledge.GraphStatsResp\x12R\n" +
	"\x12GetRelatedEntities\x12 .knowledge.GetRelatedEntitiesReq\x1a\x1a.knowledge.BatchEntityResp\x128\n" +
	"\n" +
	"ImportData\x12\x18.knowledge.ImportDataReq\x1a\x10.common.BaseRespB\x1bZ\x19Logos/proto_gen/knowledgeb\x06proto3"

var (
	file_ai_knowledge_proto_rawDescOnce sync.Once
	file_ai_knowledge_proto_rawDescData []byte
)

func file_ai_knowledge_proto_rawDescGZIP() []byte {
	file_ai_knowledge_proto_rawDescOnce.Do(func() {
		file_ai_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_knowledge_proto_rawDesc), len(file_ai_knowledge_proto_rawDesc)))
	})
	return file_ai_knowledge_proto_rawDescData
}

var file_ai_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ai_knowledge_proto_goTypes = []any{
	(*Entity)(nil),                // 0: knowledge.Entity
	(*Relation)(nil),              // 1: knowledge.Relation
	(*AddEntityReq)(nil),          // 2: knowledge.AddEntityReq
	(*UpdateEntityReq)(nil),       // 3: knowledge.UpdateEntityReq
	(*DeleteEntityReq)(nil),       // 4: knowledge.DeleteEntityReq
	(*EntityResp)(nil),            // 5: knowledge.EntityResp
	(*BatchEntityResp)(nil),       // 6: knowledge.BatchEntityResp
	(*AddRelationReq)(nil),        // 7: knowledge.AddRelationReq
	(*UpdateRelationReq)(nil),     // 8: knowledge.UpdateRelationReq
	(*DeleteRelationReq)(nil),     // 9: knowledge.DeleteRelationReq
	(*RelationResp)(nil),          // 10: knowledge.RelationResp
	(*BatchRelationResp)(nil),     // 11: knowledge.BatchRelationResp
	(*QueryEntityReq)(nil),        // 12: knowledge.QueryEntityReq
	(*QueryRelationReq)(nil),      // 13: knowledge.QueryRelationReq
	(*GraphStatsResp)(nil),        // 14: knowledge.GraphStatsResp
	(*ImportDataReq)(nil),         // 15: knowledge.ImportDataReq
	(*SearchEntityReq)(nil),       // 16: knowledge.SearchEntityReq
	(*GetByIdReq)(nil),            // 17: knowledge.GetByIdReq
	(*GetRelatedEntitiesReq)(nil), // 18: knowledge.GetRelatedEntitiesReq
	(*EmptyReq)(nil),              // 19: knowledge.EmptyReq
	nil,                           // 20: knowledge.Entity.PropertiesEntry
	nil,                           // 21: knowledge.Relation.PropertiesEntry
	nil,                           // 22: knowledge.AddEntityReq.PropertiesEntry
	nil,                           // 23: knowledge.UpdateEntityReq.PropertiesEntry
	nil,                           // 24: knowledge.AddRelationReq.PropertiesEntry
	nil,                           // 25: knowledge.UpdateRelationReq.PropertiesEntry
	nil,                           // 26: knowledge.QueryEntityReq.PropertiesEntry
	nil,                           // 27: knowledge.GraphStatsResp.EntityTypeCountEntry
	nil,                           // 28: knowledge.GraphStatsResp.RelationTypeCountEntry
	(*common.BaseResp)(nil),       // 29: common.BaseResp
}
var file_ai_knowledge_proto_depIdxs = []int32{
	20, // 0: knowledge.Entity.properties:type_name -> knowledge.Entity.PropertiesEntry
	21, // 1: knowledge.Relation.properties:type_name -> knowledge.Relation.PropertiesEntry
	22, // 2: knowledge.AddEntityReq.properties:type_name -> knowledge.AddEntityReq.PropertiesEntry
	23, // 3: knowledge.UpdateEntityReq.properties:type_name -> knowledge.UpdateEntityReq.PropertiesEntry
	29, // 4: knowledge.EntityResp.base_resp:type_name -> common.BaseResp
	0,  // 5: knowledge.EntityResp.entity:type_name -> knowledge.Entity
	29, // 6: knowledge.BatchEntityResp.base_resp:type_name -> common.BaseResp
	0,  // 7: knowledge.BatchEntityResp.entities:type_name -> knowledge.Entity
	24, // 8: knowledge.AddRelationReq.properties:type_name -> knowledge.AddRelationReq.PropertiesEntry
	25, // 9: knowledge.UpdateRelationReq.properties:type_name -> knowledge.UpdateRelationReq.PropertiesEntry
	29, // 10: knowledge.RelationResp.base_resp:type_name -> common.BaseResp
	1,  // 11: knowledge.RelationResp.relation:type_name -> knowledge.Relation
	29, // 12: knowledge.BatchRelationResp.base_resp:type_name -> common.BaseResp
	1,  // 13: knowledge.BatchRelationResp.relations:type_name -> knowledge.Relation
	26, // 14: knowledge.QueryEntityReq.properties:type_name -> knowledge.QueryEntityReq.PropertiesEntry
	29, // 15: knowledge.GraphStatsResp.base_resp:type_name -> common.BaseResp
	27, // 16: knowledge.GraphStatsResp.entity_type_count:type_name -> knowledge.GraphStatsResp.EntityTypeCountEntry
	28, // 17: knowledge.GraphStatsResp.relation_type_count:type_name -> knowledge.GraphStatsResp.RelationTypeCountEntry
	2,  // 18: knowledge.KnowledgeService.AddEntity:input_type -> knowledge.AddEntityReq
	3,  // 19: knowledge.KnowledgeService.UpdateEntity:input_type -> knowledge.UpdateEntityReq
	4,  // 20: knowledge.KnowledgeService.DeleteEntity:input_type -> knowledge.DeleteEntityReq
	17, // 21: knowledge.KnowledgeService.GetEntity:input_type -> knowledge.GetByIdReq
	12, // 22: knowledge.KnowledgeService.QueryEntities:input_type -> knowledge.QueryEntityReq
	16, // 23: knowledge.KnowledgeService.SearchEntities:input_type -> knowledge.SearchEntityReq
	7,  // 24: knowledge.KnowledgeService.AddRelation:input_type -> knowledge.AddRelationReq
	8,  // 25: knowledge.KnowledgeService.UpdateRelation:input_type -> knowledge.UpdateRelationReq
	9,  // 26: knowledge.KnowledgeService.DeleteRelation:input_type -> knowledge.DeleteRelationReq
	17, // 27: knowledge.KnowledgeService.GetRelation:input_type -> knowledge.GetByIdReq
	13, // 28: knowledge.KnowledgeService.QueryRelations:input_type -> knowledge.QueryRelationReq
	19, // 29: knowledge.KnowledgeService.GetGraphStats:input_type -> knowledge.EmptyReq
	18, // 30: knowledge.KnowledgeService.GetRelatedEntities:input_type -> knowledge.GetRelatedEntitiesReq
	15, // 31: knowledge.KnowledgeService.ImportData:input_type -> knowledge.ImportDataReq
	5,  // 32: knowledge.KnowledgeService.AddEntity:output_type -> knowledge.EntityResp
	5,  // 33: knowledge.KnowledgeService.UpdateEntity:output_type -> knowledge.EntityResp
	29, // 34: knowledge.KnowledgeService.DeleteEntity:output_type -> common.BaseResp
	5,  // 35: knowledge.KnowledgeService.GetEntity:output_type -> knowledge.EntityResp
	6,  // 36: knowledge.KnowledgeService.QueryEntities:output_type -> knowledge.BatchEntityResp
	6,  // 37: knowledge.KnowledgeService.SearchEntities:output_type -> knowledge.BatchEntityResp
	10, // 38: knowledge.KnowledgeService.AddRelation:output_type -> knowledge.RelationResp
	10, // 39: knowledge.KnowledgeService.UpdateRelation:output_type -> knowledge.RelationResp
	29, // 40: knowledge.KnowledgeService.DeleteRelation:output_type -> common.BaseResp
	10, // 41: knowledge.KnowledgeService.GetRelation:output_type -> knowledge.RelationResp
	11, // 42: knowledge.KnowledgeService.QueryRelations:output_type -> knowledge.BatchRelationResp
	14, // 43: knowledge.KnowledgeService.GetGraphStats:output_type -> knowledge.GraphStatsResp
	6,  // 44: knowledge.KnowledgeService.GetRelatedEntities:output_type -> knowledge.BatchEntityResp
	29, // 45: knowledge.KnowledgeService.ImportData:output_type -> common.BaseResp
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ai_knowledge_proto_init() }
func file_ai_knowledge_proto_init() {
	if File_ai_knowledge_proto != nil {
		return
	}
	file_ai_knowledge_proto_msgTypes[0].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[1].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[2].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[3].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[7].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[8].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[12].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[13].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[16].OneofWrappers = []any{}
	file_ai_knowledge_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_knowledge_proto_rawDesc), len(file_ai_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_knowledge_proto_goTypes,
		DependencyIndexes: file_ai_knowledge_proto_depIdxs,
		MessageInfos:      file_ai_knowledge_proto_msgTypes,
	}.Build()
	File_ai_knowledge_proto = out.File
	file_ai_knowledge_proto_goTypes = nil
	file_ai_knowledge_proto_depIdxs = nil
}
