// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ai/recommend.proto

package recommend

import (
	common "Logos/proto_gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_ai_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecommendationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecommendationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecommendationItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecommendationItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendationItem) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RecommendationItem) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *RecommendationItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RecommendationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationReq) Reset() {
	*x = RecommendationReq{}
	mi := &file_ai_recommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationReq) ProtoMessage() {}

func (x *RecommendationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationReq.ProtoReflect.Descriptor instead.
func (*RecommendationReq) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendationReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *RecommendationReq) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RecommendationReq) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type RecommendationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Items         []*RecommendationItem  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationResp) Reset() {
	*x = RecommendationResp{}
	mi := &file_ai_recommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResp) ProtoMessage() {}

func (x *RecommendationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResp.ProtoReflect.Descriptor instead.
func (*RecommendationResp) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *RecommendationResp) GetItems() []*RecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendationResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RelatedRecommendationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedRecommendationReq) Reset() {
	*x = RelatedRecommendationReq{}
	mi := &file_ai_recommend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedRecommendationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedRecommendationReq) ProtoMessage() {}

func (x *RelatedRecommendationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedRecommendationReq.ProtoReflect.Descriptor instead.
func (*RelatedRecommendationReq) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{3}
}

func (x *RelatedRecommendationReq) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RelatedRecommendationReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *RelatedRecommendationReq) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type FeedbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackReq) Reset() {
	*x = FeedbackReq{}
	mi := &file_ai_recommend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackReq) ProtoMessage() {}

func (x *FeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackReq.ProtoReflect.Descriptor instead.
func (*FeedbackReq) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{4}
}

func (x *FeedbackReq) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *FeedbackReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FeedbackReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedbackReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReq) Reset() {
	*x = HistoryReq{}
	mi := &file_ai_recommend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReq) ProtoMessage() {}

func (x *HistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReq.ProtoReflect.Descriptor instead.
func (*HistoryReq) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HistoryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *HistoryReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryItem) Reset() {
	*x = HistoryItem{}
	mi := &file_ai_recommend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryItem) ProtoMessage() {}

func (x *HistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryItem.ProtoReflect.Descriptor instead.
func (*HistoryItem) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *HistoryItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *HistoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HistoryItem) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HistoryItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Items         []*HistoryItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResp) Reset() {
	*x = HistoryResp{}
	mi := &file_ai_recommend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResp) ProtoMessage() {}

func (x *HistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResp.ProtoReflect.Descriptor instead.
func (*HistoryResp) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *HistoryResp) GetItems() []*HistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *HistoryResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BatchRecommendationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRecommendationReq) Reset() {
	*x = BatchRecommendationReq{}
	mi := &file_ai_recommend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRecommendationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecommendationReq) ProtoMessage() {}

func (x *BatchRecommendationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecommendationReq.ProtoReflect.Descriptor instead.
func (*BatchRecommendationReq) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{8}
}

func (x *BatchRecommendationReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BatchRecommendationReq) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *BatchRecommendationReq) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type RecommendationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendationItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationList) Reset() {
	*x = RecommendationList{}
	mi := &file_ai_recommend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationList) ProtoMessage() {}

func (x *RecommendationList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationList.ProtoReflect.Descriptor instead.
func (*RecommendationList) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{9}
}

func (x *RecommendationList) GetItems() []*RecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchRecommendationResp struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	BaseResp        *common.BaseResp              `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Recommendations map[int64]*RecommendationList `protobuf:"bytes,2,rep,name=recommendations,proto3" json:"recommendations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchRecommendationResp) Reset() {
	*x = BatchRecommendationResp{}
	mi := &file_ai_recommend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRecommendationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecommendationResp) ProtoMessage() {}

func (x *BatchRecommendationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_recommend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecommendationResp.ProtoReflect.Descriptor instead.
func (*BatchRecommendationResp) Descriptor() ([]byte, []int) {
	return file_ai_recommend_proto_rawDescGZIP(), []int{10}
}

func (x *BatchRecommendationResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *BatchRecommendationResp) GetRecommendations() map[int64]*RecommendationList {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_ai_recommend_proto protoreflect.FileDescriptor

const file_ai_recommend_proto_rawDesc = "" +
	"\n" +
	"\x12ai/recommend.proto\x12\trecommend\x1a\fcommon.proto\"\xf2\x01\n" +
	"\x12RecommendationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12 \n" +
	"\timage_url\x18\a \x01(\tH\x00R\bimageUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAtB\f\n" +
	"\n" +
	"_image_url\"\xf4\x01\n" +
	"\x11RecommendationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12C\n" +
	"\acontext\x18\x04 \x03(\v2).recommend.RecommendationReq.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_limit\"\x8e\x01\n" +
	"\x12RecommendationResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.recommend.RecommendationItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"~\n" +
	"\x18RelatedRecommendationReq\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_limit\"u\n" +
	"\vFeedbackReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"V\n" +
	"\n" +
	"HistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x9f\x01\n" +
	"\vHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\tR\bitemType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x80\x01\n" +
	"\vHistoryResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.recommend.HistoryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"z\n" +
	"\x16BatchRecommendationReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_limit\"I\n" +
	"\x12RecommendationList\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.recommend.RecommendationItemR\x05items\"\x8e\x02\n" +
	"\x17BatchRecommendationResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12a\n" +
	"\x0frecommendations\x18\x02 \x03(\v27.recommend.BatchRecommendationResp.RecommendationsEntryR\x0frecommendations\x1aa\n" +
	"\x14RecommendationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.recommend.RecommendationListR\x05value:\x028\x012\xb4\x03\n" +
	"\x15RecommendationService\x12Q\n" +
	"\x12GetRecommendations\x12\x1c.recommend.RecommendationReq\x1a\x1d.recommend.RecommendationResp\x12_\n" +
	"\x19GetRelatedRecommendations\x12#.recommend.RelatedRecommendationReq\x1a\x1d.recommend.RecommendationResp\x12:\n" +
	"\x0eSubmitFeedback\x12\x16.recommend.FeedbackReq\x1a\x10.common.BaseResp\x12I\n" +
	"\x18GetRecommendationHistory\x12\x15.recommend.HistoryReq\x1a\x16.recommend.HistoryResp\x12`\n" +
	"\x17BatchGetRecommendations\x12!.recommend.BatchRecommendationReq\x1a\".recommend.BatchRecommendationRespB\x1bZ\x19Logos/proto_gen/recommendb\x06proto3"

var (
	file_ai_recommend_proto_rawDescOnce sync.Once
	file_ai_recommend_proto_rawDescData []byte
)

func file_ai_recommend_proto_rawDescGZIP() []byte {
	file_ai_recommend_proto_rawDescOnce.Do(func() {
		file_ai_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_recommend_proto_rawDesc), len(file_ai_recommend_proto_rawDesc)))
	})
	return file_ai_recommend_proto_rawDescData
}

var file_ai_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ai_recommend_proto_goTypes = []any{
	(*RecommendationItem)(nil),       // 0: recommend.RecommendationItem
	(*RecommendationReq)(nil),        // 1: recommend.RecommendationReq
	(*RecommendationResp)(nil),       // 2: recommend.RecommendationResp
	(*RelatedRecommendationReq)(nil), // 3: recommend.RelatedRecommendationReq
	(*FeedbackReq)(nil),              // 4: recommend.FeedbackReq
	(*HistoryReq)(nil),               // 5: recommend.HistoryReq
	(*HistoryItem)(nil),              // 6: recommend.HistoryItem
	(*HistoryResp)(nil),              // 7: recommend.HistoryResp
	(*BatchRecommendationReq)(nil),   // 8: recommend.BatchRecommendationReq
	(*RecommendationList)(nil),       // 9: recommend.RecommendationList
	(*BatchRecommendationResp)(nil),  // 10: recommend.BatchRecommendationResp
	nil,                              // 11: recommend.RecommendationReq.ContextEntry
	nil,                              // 12: recommend.BatchRecommendationResp.RecommendationsEntry
	(*common.BaseResp)(nil),          // 13: common.BaseResp
}
var file_ai_recommend_proto_depIdxs = []int32{
	11, // 0: recommend.RecommendationReq.context:type_name -> recommend.RecommendationReq.ContextEntry
	13, // 1: recommend.RecommendationResp.base_resp:type_name -> common.BaseResp
	0,  // 2: recommend.RecommendationResp.items:type_name -> recommend.RecommendationItem
	13, // 3: recommend.HistoryResp.base_resp:type_name -> common.BaseResp
	6,  // 4: recommend.HistoryResp.items:type_name -> recommend.HistoryItem
	0,  // 5: recommend.RecommendationList.items:type_name -> recommend.RecommendationItem
	13, // 6: recommend.BatchRecommendationResp.base_resp:type_name -> common.BaseResp
	12, // 7: recommend.BatchRecommendationResp.recommendations:type_name -> recommend.BatchRecommendationResp.RecommendationsEntry
	9,  // 8: recommend.BatchRecommendationResp.RecommendationsEntry.value:type_name -> recommend.RecommendationList
	1,  // 9: recommend.RecommendationService.GetRecommendations:input_type -> recommend.RecommendationReq
	3,  // 10: recommend.RecommendationService.GetRelatedRecommendations:input_type -> recommend.RelatedRecommendationReq
	4,  // 11: recommend.RecommendationService.SubmitFeedback:input_type -> recommend.FeedbackReq
	5,  // 12: recommend.RecommendationService.GetRecommendationHistory:input_type -> recommend.HistoryReq
	8,  // 13: recommend.RecommendationService.BatchGetRecommendations:input_type -> recommend.BatchRecommendationReq
	2,  // 14: recommend.RecommendationService.GetRecommendations:output_type -> recommend.RecommendationResp
	2,  // 15: recommend.RecommendationService.GetRelatedRecommendations:output_type -> recommend.RecommendationResp
	13, // 16: recommend.RecommendationService.SubmitFeedback:output_type -> common.BaseResp
	7,  // 17: recommend.RecommendationService.GetRecommendationHistory:output_type -> recommend.HistoryResp
	10, // 18: recommend.RecommendationService.BatchGetRecommendations:output_type -> recommend.BatchRecommendationResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ai_recommend_proto_init() }
func file_ai_recommend_proto_init() {
	if File_ai_recommend_proto != nil {
		return
	}
	file_ai_recommend_proto_msgTypes[0].OneofWrappers = []any{}
	file_ai_recommend_proto_msgTypes[1].OneofWrappers = []any{}
	file_ai_recommend_proto_msgTypes[3].OneofWrappers = []any{}
	file_ai_recommend_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_recommend_proto_rawDesc), len(file_ai_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_recommend_proto_goTypes,
		DependencyIndexes: file_ai_recommend_proto_depIdxs,
		MessageInfos:      file_ai_recommend_proto_msgTypes,
	}.Build()
	File_ai_recommend_proto = out.File
	file_ai_recommend_proto_goTypes = nil
	file_ai_recommend_proto_depIdxs = nil
}
