// Code generated by Kitex v0.16.1. DO NOT EDIT.

package vectorservice

import (
	common "Noah/kitex_gen/common"
	vector "Noah/kitex_gen/vector"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCollection": kitex.NewMethodInfo(
		createCollectionHandler,
		newVectorServiceCreateCollectionArgs,
		newVectorServiceCreateCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateCollection": kitex.NewMethodInfo(
		updateCollectionHandler,
		newVectorServiceUpdateCollectionArgs,
		newVectorServiceUpdateCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteCollection": kitex.NewMethodInfo(
		deleteCollectionHandler,
		newVectorServiceDeleteCollectionArgs,
		newVectorServiceDeleteCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCollection": kitex.NewMethodInfo(
		getCollectionHandler,
		newVectorServiceGetCollectionArgs,
		newVectorServiceGetCollectionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListCollections": kitex.NewMethodInfo(
		listCollectionsHandler,
		newVectorServiceListCollectionsArgs,
		newVectorServiceListCollectionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Vectorize": kitex.NewMethodInfo(
		vectorizeHandler,
		newVectorServiceVectorizeArgs,
		newVectorServiceVectorizeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchVectorize": kitex.NewMethodInfo(
		batchVectorizeHandler,
		newVectorServiceBatchVectorizeArgs,
		newVectorServiceBatchVectorizeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Search": kitex.NewMethodInfo(
		searchHandler,
		newVectorServiceSearchArgs,
		newVectorServiceSearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TextSearch": kitex.NewMethodInfo(
		textSearchHandler,
		newVectorServiceTextSearchArgs,
		newVectorServiceTextSearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteVector": kitex.NewMethodInfo(
		deleteVectorHandler,
		newVectorServiceDeleteVectorArgs,
		newVectorServiceDeleteVectorResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchDeleteVector": kitex.NewMethodInfo(
		batchDeleteVectorHandler,
		newVectorServiceBatchDeleteVectorArgs,
		newVectorServiceBatchDeleteVectorResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	vectorServiceServiceInfo                = NewServiceInfo()
	vectorServiceServiceInfoForClient       = NewServiceInfoForClient()
	vectorServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return vectorServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return vectorServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return vectorServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VectorService"
	handlerType := (*vector.VectorService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "vector",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceCreateCollectionArgs)
	realResult := result.(*vector.VectorServiceCreateCollectionResult)
	success, err := handler.(vector.VectorService).CreateCollection(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceCreateCollectionArgs() interface{} {
	return vector.NewVectorServiceCreateCollectionArgs()
}

func newVectorServiceCreateCollectionResult() interface{} {
	return vector.NewVectorServiceCreateCollectionResult()
}

func updateCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceUpdateCollectionArgs)
	realResult := result.(*vector.VectorServiceUpdateCollectionResult)
	success, err := handler.(vector.VectorService).UpdateCollection(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceUpdateCollectionArgs() interface{} {
	return vector.NewVectorServiceUpdateCollectionArgs()
}

func newVectorServiceUpdateCollectionResult() interface{} {
	return vector.NewVectorServiceUpdateCollectionResult()
}

func deleteCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceDeleteCollectionArgs)
	realResult := result.(*vector.VectorServiceDeleteCollectionResult)
	success, err := handler.(vector.VectorService).DeleteCollection(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceDeleteCollectionArgs() interface{} {
	return vector.NewVectorServiceDeleteCollectionArgs()
}

func newVectorServiceDeleteCollectionResult() interface{} {
	return vector.NewVectorServiceDeleteCollectionResult()
}

func getCollectionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceGetCollectionArgs)
	realResult := result.(*vector.VectorServiceGetCollectionResult)
	success, err := handler.(vector.VectorService).GetCollection(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceGetCollectionArgs() interface{} {
	return vector.NewVectorServiceGetCollectionArgs()
}

func newVectorServiceGetCollectionResult() interface{} {
	return vector.NewVectorServiceGetCollectionResult()
}

func listCollectionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*vector.VectorServiceListCollectionsArgs)
	realResult := result.(*vector.VectorServiceListCollectionsResult)
	success, err := handler.(vector.VectorService).ListCollections(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceListCollectionsArgs() interface{} {
	return vector.NewVectorServiceListCollectionsArgs()
}

func newVectorServiceListCollectionsResult() interface{} {
	return vector.NewVectorServiceListCollectionsResult()
}

func vectorizeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceVectorizeArgs)
	realResult := result.(*vector.VectorServiceVectorizeResult)
	success, err := handler.(vector.VectorService).Vectorize(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceVectorizeArgs() interface{} {
	return vector.NewVectorServiceVectorizeArgs()
}

func newVectorServiceVectorizeResult() interface{} {
	return vector.NewVectorServiceVectorizeResult()
}

func batchVectorizeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceBatchVectorizeArgs)
	realResult := result.(*vector.VectorServiceBatchVectorizeResult)
	success, err := handler.(vector.VectorService).BatchVectorize(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceBatchVectorizeArgs() interface{} {
	return vector.NewVectorServiceBatchVectorizeArgs()
}

func newVectorServiceBatchVectorizeResult() interface{} {
	return vector.NewVectorServiceBatchVectorizeResult()
}

func searchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceSearchArgs)
	realResult := result.(*vector.VectorServiceSearchResult)
	success, err := handler.(vector.VectorService).Search(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceSearchArgs() interface{} {
	return vector.NewVectorServiceSearchArgs()
}

func newVectorServiceSearchResult() interface{} {
	return vector.NewVectorServiceSearchResult()
}

func textSearchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceTextSearchArgs)
	realResult := result.(*vector.VectorServiceTextSearchResult)
	success, err := handler.(vector.VectorService).TextSearch(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceTextSearchArgs() interface{} {
	return vector.NewVectorServiceTextSearchArgs()
}

func newVectorServiceTextSearchResult() interface{} {
	return vector.NewVectorServiceTextSearchResult()
}

func deleteVectorHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceDeleteVectorArgs)
	realResult := result.(*vector.VectorServiceDeleteVectorResult)
	success, err := handler.(vector.VectorService).DeleteVector(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceDeleteVectorArgs() interface{} {
	return vector.NewVectorServiceDeleteVectorArgs()
}

func newVectorServiceDeleteVectorResult() interface{} {
	return vector.NewVectorServiceDeleteVectorResult()
}

func batchDeleteVectorHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*vector.VectorServiceBatchDeleteVectorArgs)
	realResult := result.(*vector.VectorServiceBatchDeleteVectorResult)
	success, err := handler.(vector.VectorService).BatchDeleteVector(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVectorServiceBatchDeleteVectorArgs() interface{} {
	return vector.NewVectorServiceBatchDeleteVectorArgs()
}

func newVectorServiceBatchDeleteVectorResult() interface{} {
	return vector.NewVectorServiceBatchDeleteVectorResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCollection(ctx context.Context, req *vector.CreateCollectionReq) (r *vector.CollectionResp, err error) {
	var _args vector.VectorServiceCreateCollectionArgs
	_args.Req = req
	var _result vector.VectorServiceCreateCollectionResult
	if err = p.c.Call(ctx, "CreateCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCollection(ctx context.Context, req *vector.UpdateCollectionReq) (r *vector.CollectionResp, err error) {
	var _args vector.VectorServiceUpdateCollectionArgs
	_args.Req = req
	var _result vector.VectorServiceUpdateCollectionResult
	if err = p.c.Call(ctx, "UpdateCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCollection(ctx context.Context, req *vector.DeleteCollectionReq) (r *common.BaseResp, err error) {
	var _args vector.VectorServiceDeleteCollectionArgs
	_args.Req = req
	var _result vector.VectorServiceDeleteCollectionResult
	if err = p.c.Call(ctx, "DeleteCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCollection(ctx context.Context, id string) (r *vector.CollectionResp, err error) {
	var _args vector.VectorServiceGetCollectionArgs
	_args.Id = id
	var _result vector.VectorServiceGetCollectionResult
	if err = p.c.Call(ctx, "GetCollection", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCollections(ctx context.Context) (r *vector.BatchCollectionResp, err error) {
	var _args vector.VectorServiceListCollectionsArgs
	var _result vector.VectorServiceListCollectionsResult
	if err = p.c.Call(ctx, "ListCollections", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Vectorize(ctx context.Context, req *vector.VectorizeReq) (r *vector.VectorizeResp, err error) {
	var _args vector.VectorServiceVectorizeArgs
	_args.Req = req
	var _result vector.VectorServiceVectorizeResult
	if err = p.c.Call(ctx, "Vectorize", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchVectorize(ctx context.Context, req *vector.BatchVectorizeReq) (r *vector.BatchVectorizeResp, err error) {
	var _args vector.VectorServiceBatchVectorizeArgs
	_args.Req = req
	var _result vector.VectorServiceBatchVectorizeResult
	if err = p.c.Call(ctx, "BatchVectorize", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Search(ctx context.Context, req *vector.SearchReq) (r *vector.SearchResp, err error) {
	var _args vector.VectorServiceSearchArgs
	_args.Req = req
	var _result vector.VectorServiceSearchResult
	if err = p.c.Call(ctx, "Search", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TextSearch(ctx context.Context, req *vector.TextSearchReq) (r *vector.SearchResp, err error) {
	var _args vector.VectorServiceTextSearchArgs
	_args.Req = req
	var _result vector.VectorServiceTextSearchResult
	if err = p.c.Call(ctx, "TextSearch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteVector(ctx context.Context, req *vector.DeleteVectorReq) (r *common.BaseResp, err error) {
	var _args vector.VectorServiceDeleteVectorArgs
	_args.Req = req
	var _result vector.VectorServiceDeleteVectorResult
	if err = p.c.Call(ctx, "DeleteVector", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchDeleteVector(ctx context.Context, req *vector.BatchDeleteVectorReq) (r *common.BaseResp, err error) {
	var _args vector.VectorServiceBatchDeleteVectorArgs
	_args.Req = req
	var _result vector.VectorServiceBatchDeleteVectorResult
	if err = p.c.Call(ctx, "BatchDeleteVector", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
