// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ai/vector.proto

package vector

import (
	common "Logos/proto_gen/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorModelType int32

const (
	VectorModelType_BERT         VectorModelType = 0
	VectorModelType_Word2Vec     VectorModelType = 1
	VectorModelType_GloVe        VectorModelType = 2
	VectorModelType_fastText     VectorModelType = 3
	VectorModelType_SentenceBERT VectorModelType = 4
	VectorModelType_Custom       VectorModelType = 5
)

// Enum value maps for VectorModelType.
var (
	VectorModelType_name = map[int32]string{
		0: "BERT",
		1: "Word2Vec",
		2: "GloVe",
		3: "fastText",
		4: "SentenceBERT",
		5: "Custom",
	}
	VectorModelType_value = map[string]int32{
		"BERT":         0,
		"Word2Vec":     1,
		"GloVe":        2,
		"fastText":     3,
		"SentenceBERT": 4,
		"Custom":       5,
	}
)

func (x VectorModelType) Enum() *VectorModelType {
	p := new(VectorModelType)
	*p = x
	return p
}

func (x VectorModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VectorModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_vector_proto_enumTypes[0].Descriptor()
}

func (VectorModelType) Type() protoreflect.EnumType {
	return &file_ai_vector_proto_enumTypes[0]
}

func (x VectorModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VectorModelType.Descriptor instead.
func (VectorModelType) EnumDescriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{0}
}

type IndexType int32

const (
	IndexType_FLAT     IndexType = 0
	IndexType_IVF_FLAT IndexType = 1
	IndexType_IVF_PQ   IndexType = 2
	IndexType_HNSW     IndexType = 3
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "FLAT",
		1: "IVF_FLAT",
		2: "IVF_PQ",
		3: "HNSW",
	}
	IndexType_value = map[string]int32{
		"FLAT":     0,
		"IVF_FLAT": 1,
		"IVF_PQ":   2,
		"HNSW":     3,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_vector_proto_enumTypes[1].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_ai_vector_proto_enumTypes[1]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{1}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float64              `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_ai_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Vector) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type VectorCollection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelType        VectorModelType        `protobuf:"varint,3,opt,name=model_type,json=modelType,proto3,enum=vector.VectorModelType" json:"model_type,omitempty"`
	IndexType        IndexType              `protobuf:"varint,4,opt,name=index_type,json=indexType,proto3,enum=vector.IndexType" json:"index_type,omitempty"`
	Dimension        int32                  `protobuf:"varint,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Parameters       map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Size             int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VlmModel         string                 `protobuf:"bytes,10,opt,name=vlm_model,json=vlmModel,proto3" json:"vlm_model,omitempty"`
	VlmBaseUrl       string                 `protobuf:"bytes,11,opt,name=vlm_base_url,json=vlmBaseUrl,proto3" json:"vlm_base_url,omitempty"`
	VlmApiKey        string                 `protobuf:"bytes,12,opt,name=vlm_api_key,json=vlmApiKey,proto3" json:"vlm_api_key,omitempty"`
	LlmModel         string                 `protobuf:"bytes,13,opt,name=llm_model,json=llmModel,proto3" json:"llm_model,omitempty"`
	LlmBaseUrl       string                 `protobuf:"bytes,14,opt,name=llm_base_url,json=llmBaseUrl,proto3" json:"llm_base_url,omitempty"`
	LlmApiKey        string                 `protobuf:"bytes,15,opt,name=llm_api_key,json=llmApiKey,proto3" json:"llm_api_key,omitempty"`
	AsrModel         string                 `protobuf:"bytes,16,opt,name=asr_model,json=asrModel,proto3" json:"asr_model,omitempty"`
	AsrBaseUrl       string                 `protobuf:"bytes,17,opt,name=asr_base_url,json=asrBaseUrl,proto3" json:"asr_base_url,omitempty"`
	AsrApiKey        string                 `protobuf:"bytes,18,opt,name=asr_api_key,json=asrApiKey,proto3" json:"asr_api_key,omitempty"`
	EmbeddingModel   string                 `protobuf:"bytes,19,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingBaseUrl string                 `protobuf:"bytes,20,opt,name=embedding_base_url,json=embeddingBaseUrl,proto3" json:"embedding_base_url,omitempty"`
	EmbeddingApiKey  string                 `protobuf:"bytes,21,opt,name=embedding_api_key,json=embeddingApiKey,proto3" json:"embedding_api_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VectorCollection) Reset() {
	*x = VectorCollection{}
	mi := &file_ai_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorCollection) ProtoMessage() {}

func (x *VectorCollection) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorCollection.ProtoReflect.Descriptor instead.
func (*VectorCollection) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{1}
}

func (x *VectorCollection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorCollection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VectorCollection) GetModelType() VectorModelType {
	if x != nil {
		return x.ModelType
	}
	return VectorModelType_BERT
}

func (x *VectorCollection) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_FLAT
}

func (x *VectorCollection) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *VectorCollection) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *VectorCollection) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VectorCollection) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VectorCollection) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *VectorCollection) GetVlmModel() string {
	if x != nil {
		return x.VlmModel
	}
	return ""
}

func (x *VectorCollection) GetVlmBaseUrl() string {
	if x != nil {
		return x.VlmBaseUrl
	}
	return ""
}

func (x *VectorCollection) GetVlmApiKey() string {
	if x != nil {
		return x.VlmApiKey
	}
	return ""
}

func (x *VectorCollection) GetLlmModel() string {
	if x != nil {
		return x.LlmModel
	}
	return ""
}

func (x *VectorCollection) GetLlmBaseUrl() string {
	if x != nil {
		return x.LlmBaseUrl
	}
	return ""
}

func (x *VectorCollection) GetLlmApiKey() string {
	if x != nil {
		return x.LlmApiKey
	}
	return ""
}

func (x *VectorCollection) GetAsrModel() string {
	if x != nil {
		return x.AsrModel
	}
	return ""
}

func (x *VectorCollection) GetAsrBaseUrl() string {
	if x != nil {
		return x.AsrBaseUrl
	}
	return ""
}

func (x *VectorCollection) GetAsrApiKey() string {
	if x != nil {
		return x.AsrApiKey
	}
	return ""
}

func (x *VectorCollection) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *VectorCollection) GetEmbeddingBaseUrl() string {
	if x != nil {
		return x.EmbeddingBaseUrl
	}
	return ""
}

func (x *VectorCollection) GetEmbeddingApiKey() string {
	if x != nil {
		return x.EmbeddingApiKey
	}
	return ""
}

type CreateCollectionReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelType        VectorModelType        `protobuf:"varint,2,opt,name=model_type,json=modelType,proto3,enum=vector.VectorModelType" json:"model_type,omitempty"`
	IndexType        IndexType              `protobuf:"varint,3,opt,name=index_type,json=indexType,proto3,enum=vector.IndexType" json:"index_type,omitempty"`
	Dimension        int32                  `protobuf:"varint,4,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Parameters       map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VlmModel         string                 `protobuf:"bytes,6,opt,name=vlm_model,json=vlmModel,proto3" json:"vlm_model,omitempty"`
	VlmBaseUrl       string                 `protobuf:"bytes,7,opt,name=vlm_base_url,json=vlmBaseUrl,proto3" json:"vlm_base_url,omitempty"`
	VlmApiKey        string                 `protobuf:"bytes,8,opt,name=vlm_api_key,json=vlmApiKey,proto3" json:"vlm_api_key,omitempty"`
	LlmModel         string                 `protobuf:"bytes,9,opt,name=llm_model,json=llmModel,proto3" json:"llm_model,omitempty"`
	LlmBaseUrl       string                 `protobuf:"bytes,10,opt,name=llm_base_url,json=llmBaseUrl,proto3" json:"llm_base_url,omitempty"`
	LlmApiKey        string                 `protobuf:"bytes,11,opt,name=llm_api_key,json=llmApiKey,proto3" json:"llm_api_key,omitempty"`
	AsrModel         string                 `protobuf:"bytes,12,opt,name=asr_model,json=asrModel,proto3" json:"asr_model,omitempty"`
	AsrBaseUrl       string                 `protobuf:"bytes,13,opt,name=asr_base_url,json=asrBaseUrl,proto3" json:"asr_base_url,omitempty"`
	AsrApiKey        string                 `protobuf:"bytes,14,opt,name=asr_api_key,json=asrApiKey,proto3" json:"asr_api_key,omitempty"`
	EmbeddingModel   string                 `protobuf:"bytes,15,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingBaseUrl string                 `protobuf:"bytes,16,opt,name=embedding_base_url,json=embeddingBaseUrl,proto3" json:"embedding_base_url,omitempty"`
	EmbeddingApiKey  string                 `protobuf:"bytes,17,opt,name=embedding_api_key,json=embeddingApiKey,proto3" json:"embedding_api_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCollectionReq) Reset() {
	*x = CreateCollectionReq{}
	mi := &file_ai_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionReq) ProtoMessage() {}

func (x *CreateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionReq.ProtoReflect.Descriptor instead.
func (*CreateCollectionReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionReq) GetModelType() VectorModelType {
	if x != nil {
		return x.ModelType
	}
	return VectorModelType_BERT
}

func (x *CreateCollectionReq) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_FLAT
}

func (x *CreateCollectionReq) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionReq) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateCollectionReq) GetVlmModel() string {
	if x != nil {
		return x.VlmModel
	}
	return ""
}

func (x *CreateCollectionReq) GetVlmBaseUrl() string {
	if x != nil {
		return x.VlmBaseUrl
	}
	return ""
}

func (x *CreateCollectionReq) GetVlmApiKey() string {
	if x != nil {
		return x.VlmApiKey
	}
	return ""
}

func (x *CreateCollectionReq) GetLlmModel() string {
	if x != nil {
		return x.LlmModel
	}
	return ""
}

func (x *CreateCollectionReq) GetLlmBaseUrl() string {
	if x != nil {
		return x.LlmBaseUrl
	}
	return ""
}

func (x *CreateCollectionReq) GetLlmApiKey() string {
	if x != nil {
		return x.LlmApiKey
	}
	return ""
}

func (x *CreateCollectionReq) GetAsrModel() string {
	if x != nil {
		return x.AsrModel
	}
	return ""
}

func (x *CreateCollectionReq) GetAsrBaseUrl() string {
	if x != nil {
		return x.AsrBaseUrl
	}
	return ""
}

func (x *CreateCollectionReq) GetAsrApiKey() string {
	if x != nil {
		return x.AsrApiKey
	}
	return ""
}

func (x *CreateCollectionReq) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *CreateCollectionReq) GetEmbeddingBaseUrl() string {
	if x != nil {
		return x.EmbeddingBaseUrl
	}
	return ""
}

func (x *CreateCollectionReq) GetEmbeddingApiKey() string {
	if x != nil {
		return x.EmbeddingApiKey
	}
	return ""
}

type UpdateCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionReq) Reset() {
	*x = UpdateCollectionReq{}
	mi := &file_ai_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionReq) ProtoMessage() {}

func (x *UpdateCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionReq.ProtoReflect.Descriptor instead.
func (*UpdateCollectionReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCollectionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCollectionReq) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DeleteCollectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionReq) Reset() {
	*x = DeleteCollectionReq{}
	mi := &file_ai_vector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionReq) ProtoMessage() {}

func (x *DeleteCollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionReq.ProtoReflect.Descriptor instead.
func (*DeleteCollectionReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCollectionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Collection    *VectorCollection      `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionResp) Reset() {
	*x = CollectionResp{}
	mi := &file_ai_vector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionResp) ProtoMessage() {}

func (x *CollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionResp.ProtoReflect.Descriptor instead.
func (*CollectionResp) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{5}
}

func (x *CollectionResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *CollectionResp) GetCollection() *VectorCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type BatchCollectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Collections   []*VectorCollection    `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCollectionResp) Reset() {
	*x = BatchCollectionResp{}
	mi := &file_ai_vector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCollectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCollectionResp) ProtoMessage() {}

func (x *BatchCollectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCollectionResp.ProtoReflect.Descriptor instead.
func (*BatchCollectionResp) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCollectionResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *BatchCollectionResp) GetCollections() []*VectorCollection {
	if x != nil {
		return x.Collections
	}
	return nil
}

type VectorizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeReq) Reset() {
	*x = VectorizeReq{}
	mi := &file_ai_vector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeReq) ProtoMessage() {}

func (x *VectorizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeReq.ProtoReflect.Descriptor instead.
func (*VectorizeReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{7}
}

func (x *VectorizeReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *VectorizeReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *VectorizeReq) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MapWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapWrapper) Reset() {
	*x = MapWrapper{}
	mi := &file_ai_vector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapWrapper) ProtoMessage() {}

func (x *MapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapWrapper.ProtoReflect.Descriptor instead.
func (*MapWrapper) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{8}
}

func (x *MapWrapper) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchVectorizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	CollectionId  string                 `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	MetadataList  []*MapWrapper          `protobuf:"bytes,3,rep,name=metadata_list,json=metadataList,proto3" json:"metadata_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchVectorizeReq) Reset() {
	*x = BatchVectorizeReq{}
	mi := &file_ai_vector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchVectorizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchVectorizeReq) ProtoMessage() {}

func (x *BatchVectorizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchVectorizeReq.ProtoReflect.Descriptor instead.
func (*BatchVectorizeReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{9}
}

func (x *BatchVectorizeReq) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchVectorizeReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *BatchVectorizeReq) GetMetadataList() []*MapWrapper {
	if x != nil {
		return x.MetadataList
	}
	return nil
}

type VectorizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeResp) Reset() {
	*x = VectorizeResp{}
	mi := &file_ai_vector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeResp) ProtoMessage() {}

func (x *VectorizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeResp.ProtoReflect.Descriptor instead.
func (*VectorizeResp) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{10}
}

func (x *VectorizeResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *VectorizeResp) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type BatchVectorizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchVectorizeResp) Reset() {
	*x = BatchVectorizeResp{}
	mi := &file_ai_vector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchVectorizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchVectorizeResp) ProtoMessage() {}

func (x *BatchVectorizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchVectorizeResp.ProtoReflect.Descriptor instead.
func (*BatchVectorizeResp) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{11}
}

func (x *BatchVectorizeResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *BatchVectorizeResp) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	QueryVector   []float64              `protobuf:"fixed64,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Threshold     *float64               `protobuf:"fixed64,4,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	Filter        map[string]string      `protobuf:"bytes,5,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_ai_vector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{12}
}

func (x *SearchReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *SearchReq) GetQueryVector() []float64 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchReq) GetThreshold() float64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *SearchReq) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchResultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorId      string                 `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultItem) Reset() {
	*x = SearchResultItem{}
	mi := &file_ai_vector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultItem) ProtoMessage() {}

func (x *SearchResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultItem.ProtoReflect.Descriptor instead.
func (*SearchResultItem) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResultItem) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *SearchResultItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResultItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Results       []*SearchResultItem    `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	SearchTime    int64                  `protobuf:"varint,3,opt,name=search_time,json=searchTime,proto3" json:"search_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_ai_vector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *SearchResp) GetResults() []*SearchResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResp) GetSearchTime() int64 {
	if x != nil {
		return x.SearchTime
	}
	return 0
}

type TextSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Threshold     *float64               `protobuf:"fixed64,4,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	Filter        map[string]string      `protobuf:"bytes,5,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSearchReq) Reset() {
	*x = TextSearchReq{}
	mi := &file_ai_vector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchReq) ProtoMessage() {}

func (x *TextSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchReq.ProtoReflect.Descriptor instead.
func (*TextSearchReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{15}
}

func (x *TextSearchReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *TextSearchReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextSearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *TextSearchReq) GetThreshold() float64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *TextSearchReq) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type DeleteVectorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	VectorId      string                 `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorReq) Reset() {
	*x = DeleteVectorReq{}
	mi := &file_ai_vector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorReq) ProtoMessage() {}

func (x *DeleteVectorReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorReq.ProtoReflect.Descriptor instead.
func (*DeleteVectorReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteVectorReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *DeleteVectorReq) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

type BatchDeleteVectorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	VectorIds     []string               `protobuf:"bytes,2,rep,name=vector_ids,json=vectorIds,proto3" json:"vector_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteVectorReq) Reset() {
	*x = BatchDeleteVectorReq{}
	mi := &file_ai_vector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteVectorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteVectorReq) ProtoMessage() {}

func (x *BatchDeleteVectorReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteVectorReq.ProtoReflect.Descriptor instead.
func (*BatchDeleteVectorReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{17}
}

func (x *BatchDeleteVectorReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *BatchDeleteVectorReq) GetVectorIds() []string {
	if x != nil {
		return x.VectorIds
	}
	return nil
}

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_ai_vector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{18}
}

func (x *GetByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	mi := &file_ai_vector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_ai_vector_proto_rawDescGZIP(), []int{19}
}

type ListVectorsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  string                 `protobuf:"bytes,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVectorsReq) Reset() {
	*x = ListVectorsReq{}
	mi := &file_ai_vector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVectorsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVectorsReq) ProtoMessage() {}

func (x *ListVectorsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListVectorsReq) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListVectorsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVectorsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VectorPreviewItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorPreviewItem) Reset() {
	*x = VectorPreviewItem{}
	mi := &file_ai_vector_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorPreviewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorPreviewItem) ProtoMessage() {}

func (x *VectorPreviewItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VectorPreviewItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorPreviewItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VectorPreviewItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VectorPreviewItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListVectorsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *common.BaseResp       `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	Vectors       []*VectorPreviewItem   `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVectorsResp) Reset() {
	*x = ListVectorsResp{}
	mi := &file_ai_vector_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVectorsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVectorsResp) ProtoMessage() {}

func (x *ListVectorsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_vector_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListVectorsResp) GetBaseResp() *common.BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *ListVectorsResp) GetVectors() []*VectorPreviewItem {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *ListVectorsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVectorsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVectorsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_ai_vector_proto protoreflect.FileDescriptor

const file_ai_vector_proto_rawDesc = "" +
	"\n" +
	"\x0fai/vector.proto\x12\x06vector\x1a\fcommon.proto\"\xc6\x01\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x01R\x06values\x128\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1c.vector.Vector.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x06\n" +
	"\x10VectorCollection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\n" +
	"model_type\x18\x03 \x01(\x0e2\x17.vector.VectorModelTypeR\tmodelType\x120\n" +
	"\n" +
	"index_type\x18\x04 \x01(\x0e2\x11.vector.IndexTypeR\tindexType\x12\x1c\n" +
	"\tdimension\x18\x05 \x01(\x05R\tdimension\x12H\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v2(.vector.VectorCollection.ParametersEntryR\n" +
	"parameters\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tvlm_model\x18\n" +
	" \x01(\tR\bvlmModel\x12 \n" +
	"\fvlm_base_url\x18\v \x01(\tR\n" +
	"vlmBaseUrl\x12\x1e\n" +
	"\vvlm_api_key\x18\f \x01(\tR\tvlmApiKey\x12\x1b\n" +
	"\tllm_model\x18\r \x01(\tR\bllmModel\x12 \n" +
	"\fllm_base_url\x18\x0e \x01(\tR\n" +
	"llmBaseUrl\x12\x1e\n" +
	"\vllm_api_key\x18\x0f \x01(\tR\tllmApiKey\x12\x1b\n" +
	"\tasr_model\x18\x10 \x01(\tR\basrModel\x12 \n" +
	"\fasr_base_url\x18\x11 \x01(\tR\n" +
	"asrBaseUrl\x12\x1e\n" +
	"\vasr_api_key\x18\x12 \x01(\tR\tasrApiKey\x12'\n" +
	"\x0fembedding_model\x18\x13 \x01(\tR\x0eembeddingModel\x12,\n" +
	"\x12embedding_base_url\x18\x14 \x01(\tR\x10embeddingBaseUrl\x12*\n" +
	"\x11embedding_api_key\x18\x15 \x01(\tR\x0fembeddingApiKey\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x05\n" +
	"\x13CreateCollectionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\n" +
	"model_type\x18\x02 \x01(\x0e2\x17.vector.VectorModelTypeR\tmodelType\x120\n" +
	"\n" +
	"index_type\x18\x03 \x01(\x0e2\x11.vector.IndexTypeR\tindexType\x12\x1c\n" +
	"\tdimension\x18\x04 \x01(\x05R\tdimension\x12K\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2+.vector.CreateCollectionReq.ParametersEntryR\n" +
	"parameters\x12\x1b\n" +
	"\tvlm_model\x18\x06 \x01(\tR\bvlmModel\x12 \n" +
	"\fvlm_base_url\x18\a \x01(\tR\n" +
	"vlmBaseUrl\x12\x1e\n" +
	"\vvlm_api_key\x18\b \x01(\tR\tvlmApiKey\x12\x1b\n" +
	"\tllm_model\x18\t \x01(\tR\bllmModel\x12 \n" +
	"\fllm_base_url\x18\n" +
	" \x01(\tR\n" +
	"llmBaseUrl\x12\x1e\n" +
	"\vllm_api_key\x18\v \x01(\tR\tllmApiKey\x12\x1b\n" +
	"\tasr_model\x18\f \x01(\tR\basrModel\x12 \n" +
	"\fasr_base_url\x18\r \x01(\tR\n" +
	"asrBaseUrl\x12\x1e\n" +
	"\vasr_api_key\x18\x0e \x01(\tR\tasrApiKey\x12'\n" +
	"\x0fembedding_model\x18\x0f \x01(\tR\x0eembeddingModel\x12,\n" +
	"\x12embedding_base_url\x18\x10 \x01(\tR\x10embeddingBaseUrl\x12*\n" +
	"\x11embedding_api_key\x18\x11 \x01(\tR\x0fembeddingApiKey\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x13UpdateCollectionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.vector.UpdateCollectionReq.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_name\"%\n" +
	"\x13DeleteCollectionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x0eCollectionResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x128\n" +
	"\n" +
	"collection\x18\x02 \x01(\v2\x18.vector.VectorCollectionR\n" +
	"collection\"\x80\x01\n" +
	"\x13BatchCollectionResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12:\n" +
	"\vcollections\x18\x02 \x03(\v2\x18.vector.VectorCollectionR\vcollections\"\xc4\x01\n" +
	"\fVectorizeReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".vector.VectorizeReq.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\n" +
	"MapWrapper\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.vector.MapWrapper.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x11BatchVectorizeReq\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\tR\fcollectionId\x127\n" +
	"\rmetadata_list\x18\x03 \x03(\v2\x12.vector.MapWrapperR\fmetadataList\"f\n" +
	"\rVectorizeResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12&\n" +
	"\x06vector\x18\x02 \x01(\v2\x0e.vector.VectorR\x06vector\"m\n" +
	"\x12BatchVectorizeResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x12(\n" +
	"\avectors\x18\x02 \x03(\v2\x0e.vector.VectorR\avectors\"\x8b\x02\n" +
	"\tSearchReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x01R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12!\n" +
	"\tthreshold\x18\x04 \x01(\x01H\x00R\tthreshold\x88\x01\x01\x125\n" +
	"\x06filter\x18\x05 \x03(\v2\x1d.vector.SearchReq.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_threshold\"\xc6\x01\n" +
	"\x10SearchResultItem\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\tR\bvectorId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.vector.SearchResultItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\n" +
	"SearchResp\x12-\n" +
	"\tbase_resp\x18\x01 \x01(\v2\x10.common.BaseRespR\bbaseResp\x122\n" +
	"\aresults\x18\x02 \x03(\v2\x18.vector.SearchResultItemR\aresults\x12\x1f\n" +
	"\vsearch_time\x18\x03 \x01(\x03R\n" +
	"searchTime\"\x84\x02\n" +
	"\rTextSearchReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12!\n" +
	"\tthreshold\x18\x04 \x01(\x01H\x00R\tthreshold\x88\x01\x01\x129\n" +
	"\x06filter\x18\x05 \x03(\v2!.vector.TextSearchReq.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_threshold\"S\n" +
	"\x0fDeleteVectorReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1b\n" +
	"\tvector_id\x18\x02 \x01(\tR\bvectorId\"Z\n" +
	"\x14BatchDeleteVectorReq\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\tR\fcollectionId\x12\x1d\n" +
	"\n" +
	"vector_ids\x18\x02 \x03(\tR\tvectorIds\"\x1c\n" +
	"\n" +
	"GetByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\n" +
	"\n" +
	"\bEmptyReq*`\n" +
	"\x0fVectorModelType\x12\b\n" +
	"\x04BERT\x10\x00\x12\f\n" +
	"\bWord2Vec\x10\x01\x12\t\n" +
	"\x05GloVe\x10\x02\x12\f\n" +
	"\bfastText\x10\x03\x12\x10\n" +
	"\fSentenceBERT\x10\x04\x12\n" +
	"\n" +
	"\x06Custom\x10\x05*9\n" +
	"\tIndexType\x12\b\n" +
	"\x04FLAT\x10\x00\x12\f\n" +
	"\bIVF_FLAT\x10\x01\x12\n" +
	"\n" +
	"\x06IVF_PQ\x10\x02\x12\b\n" +
	"\x04HNSW\x10\x032\xd0\x05\n" +
	"\rVectorService\x12G\n" +
	"\x10CreateCollection\x12\x1b.vector.CreateCollectionReq\x1a\x16.vector.CollectionResp\x12G\n" +
	"\x10UpdateCollection\x12\x1b.vector.UpdateCollectionReq\x1a\x16.vector.CollectionResp\x12A\n" +
	"\x10DeleteCollection\x12\x1b.vector.DeleteCollectionReq\x1a\x10.common.BaseResp\x12;\n" +
	"\rGetCollection\x12\x12.vector.GetByIdReq\x1a\x16.vector.CollectionResp\x12@\n" +
	"\x0fListCollections\x12\x10.vector.EmptyReq\x1a\x1b.vector.BatchCollectionResp\x128\n" +
	"\tVectorize\x12\x14.vector.VectorizeReq\x1a\x15.vector.VectorizeResp\x12G\n" +
	"\x0eBatchVectorize\x12\x19.vector.BatchVectorizeReq\x1a\x1a.vector.BatchVectorizeResp\x12/\n" +
	"\x06Search\x12\x11.vector.SearchReq\x1a\x12.vector.SearchResp\x127\n" +
	"\n" +
	"TextSearch\x12\x15.vector.TextSearchReq\x1a\x12.vector.SearchResp\x129\n" +
	"\fDeleteVector\x12\x17.vector.DeleteVectorReq\x1a\x10.common.BaseResp\x12C\n" +
	"\x11BatchDeleteVector\x12\x1c.vector.BatchDeleteVectorReq\x1a\x10.common.BaseRespB\x18Z\x16Logos/proto_gen/vectorb\x06proto3"

var (
	file_ai_vector_proto_rawDescOnce sync.Once
	file_ai_vector_proto_rawDescData []byte
)

func file_ai_vector_proto_rawDescGZIP() []byte {
	file_ai_vector_proto_rawDescOnce.Do(func() {
		file_ai_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_vector_proto_rawDesc), len(file_ai_vector_proto_rawDesc)))
	})
	return file_ai_vector_proto_rawDescData
}

var file_ai_vector_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ai_vector_proto_goTypes = []any{
	(VectorModelType)(0),         // 0: vector.VectorModelType
	(IndexType)(0),               // 1: vector.IndexType
	(*Vector)(nil),               // 2: vector.Vector
	(*VectorCollection)(nil),     // 3: vector.VectorCollection
	(*CreateCollectionReq)(nil),  // 4: vector.CreateCollectionReq
	(*UpdateCollectionReq)(nil),  // 5: vector.UpdateCollectionReq
	(*DeleteCollectionReq)(nil),  // 6: vector.DeleteCollectionReq
	(*CollectionResp)(nil),       // 7: vector.CollectionResp
	(*BatchCollectionResp)(nil),  // 8: vector.BatchCollectionResp
	(*VectorizeReq)(nil),         // 9: vector.VectorizeReq
	(*MapWrapper)(nil),           // 10: vector.MapWrapper
	(*BatchVectorizeReq)(nil),    // 11: vector.BatchVectorizeReq
	(*VectorizeResp)(nil),        // 12: vector.VectorizeResp
	(*BatchVectorizeResp)(nil),   // 13: vector.BatchVectorizeResp
	(*SearchReq)(nil),            // 14: vector.SearchReq
	(*SearchResultItem)(nil),     // 15: vector.SearchResultItem
	(*SearchResp)(nil),           // 16: vector.SearchResp
	(*TextSearchReq)(nil),        // 17: vector.TextSearchReq
	(*DeleteVectorReq)(nil),      // 18: vector.DeleteVectorReq
	(*BatchDeleteVectorReq)(nil), // 19: vector.BatchDeleteVectorReq
	(*GetByIdReq)(nil),           // 20: vector.GetByIdReq
	(*EmptyReq)(nil),             // 21: vector.EmptyReq
	nil,                          // 22: vector.Vector.MetadataEntry
	nil,                          // 23: vector.VectorCollection.ParametersEntry
	nil,                          // 24: vector.CreateCollectionReq.ParametersEntry
	nil,                          // 25: vector.UpdateCollectionReq.ParametersEntry
	nil,                          // 26: vector.VectorizeReq.MetadataEntry
	nil,                          // 27: vector.MapWrapper.DataEntry
	nil,                          // 28: vector.SearchReq.FilterEntry
	nil,                          // 29: vector.SearchResultItem.MetadataEntry
	nil,                          // 30: vector.TextSearchReq.FilterEntry
	(*common.BaseResp)(nil),      // 31: common.BaseResp
}
var file_ai_vector_proto_depIdxs = []int32{
	22, // 0: vector.Vector.metadata:type_name -> vector.Vector.MetadataEntry
	0,  // 1: vector.VectorCollection.model_type:type_name -> vector.VectorModelType
	1,  // 2: vector.VectorCollection.index_type:type_name -> vector.IndexType
	23, // 3: vector.VectorCollection.parameters:type_name -> vector.VectorCollection.ParametersEntry
	0,  // 4: vector.CreateCollectionReq.model_type:type_name -> vector.VectorModelType
	1,  // 5: vector.CreateCollectionReq.index_type:type_name -> vector.IndexType
	24, // 6: vector.CreateCollectionReq.parameters:type_name -> vector.CreateCollectionReq.ParametersEntry
	25, // 7: vector.UpdateCollectionReq.parameters:type_name -> vector.UpdateCollectionReq.ParametersEntry
	31, // 8: vector.CollectionResp.base_resp:type_name -> common.BaseResp
	3,  // 9: vector.CollectionResp.collection:type_name -> vector.VectorCollection
	31, // 10: vector.BatchCollectionResp.base_resp:type_name -> common.BaseResp
	3,  // 11: vector.BatchCollectionResp.collections:type_name -> vector.VectorCollection
	26, // 12: vector.VectorizeReq.metadata:type_name -> vector.VectorizeReq.MetadataEntry
	27, // 13: vector.MapWrapper.data:type_name -> vector.MapWrapper.DataEntry
	10, // 14: vector.BatchVectorizeReq.metadata_list:type_name -> vector.MapWrapper
	31, // 15: vector.VectorizeResp.base_resp:type_name -> common.BaseResp
	2,  // 16: vector.VectorizeResp.vector:type_name -> vector.Vector
	31, // 17: vector.BatchVectorizeResp.base_resp:type_name -> common.BaseResp
	2,  // 18: vector.BatchVectorizeResp.vectors:type_name -> vector.Vector
	28, // 19: vector.SearchReq.filter:type_name -> vector.SearchReq.FilterEntry
	29, // 20: vector.SearchResultItem.metadata:type_name -> vector.SearchResultItem.MetadataEntry
	31, // 21: vector.SearchResp.base_resp:type_name -> common.BaseResp
	15, // 22: vector.SearchResp.results:type_name -> vector.SearchResultItem
	30, // 23: vector.TextSearchReq.filter:type_name -> vector.TextSearchReq.FilterEntry
	4,  // 24: vector.VectorService.CreateCollection:input_type -> vector.CreateCollectionReq
	5,  // 25: vector.VectorService.UpdateCollection:input_type -> vector.UpdateCollectionReq
	6,  // 26: vector.VectorService.DeleteCollection:input_type -> vector.DeleteCollectionReq
	20, // 27: vector.VectorService.GetCollection:input_type -> vector.GetByIdReq
	21, // 28: vector.VectorService.ListCollections:input_type -> vector.EmptyReq
	9,  // 29: vector.VectorService.Vectorize:input_type -> vector.VectorizeReq
	11, // 30: vector.VectorService.BatchVectorize:input_type -> vector.BatchVectorizeReq
	14, // 31: vector.VectorService.Search:input_type -> vector.SearchReq
	17, // 32: vector.VectorService.TextSearch:input_type -> vector.TextSearchReq
	18, // 33: vector.VectorService.DeleteVector:input_type -> vector.DeleteVectorReq
	19, // 34: vector.VectorService.BatchDeleteVector:input_type -> vector.BatchDeleteVectorReq
	7,  // 35: vector.VectorService.CreateCollection:output_type -> vector.CollectionResp
	7,  // 36: vector.VectorService.UpdateCollection:output_type -> vector.CollectionResp
	31, // 37: vector.VectorService.DeleteCollection:output_type -> common.BaseResp
	7,  // 38: vector.VectorService.GetCollection:output_type -> vector.CollectionResp
	8,  // 39: vector.VectorService.ListCollections:output_type -> vector.BatchCollectionResp
	12, // 40: vector.VectorService.Vectorize:output_type -> vector.VectorizeResp
	13, // 41: vector.VectorService.BatchVectorize:output_type -> vector.BatchVectorizeResp
	16, // 42: vector.VectorService.Search:output_type -> vector.SearchResp
	16, // 43: vector.VectorService.TextSearch:output_type -> vector.SearchResp
	31, // 44: vector.VectorService.DeleteVector:output_type -> common.BaseResp
	31, // 45: vector.VectorService.BatchDeleteVector:output_type -> common.BaseResp
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_ai_vector_proto_init() }
func file_ai_vector_proto_init() {
	if File_ai_vector_proto != nil {
		return
	}
	file_ai_vector_proto_msgTypes[3].OneofWrappers = []any{}
	file_ai_vector_proto_msgTypes[12].OneofWrappers = []any{}
	file_ai_vector_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_vector_proto_rawDesc), len(file_ai_vector_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_vector_proto_goTypes,
		DependencyIndexes: file_ai_vector_proto_depIdxs,
		EnumInfos:         file_ai_vector_proto_enumTypes,
		MessageInfos:      file_ai_vector_proto_msgTypes,
	}.Build()
	File_ai_vector_proto = out.File
	file_ai_vector_proto_goTypes = nil
	file_ai_vector_proto_depIdxs = nil
}
