// Code generated by Kitex v0.16.1. DO NOT EDIT.

package qaservice

import (
	common "Noah/kitex_gen/common"
	question "Noah/kitex_gen/question"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AskQuestion(ctx context.Context, req *question.QuestionReq, callOptions ...callopt.Option) (r *question.AnswerResp, err error)
	BatchAskQuestions(ctx context.Context, req *question.BatchQuestionReq, callOptions ...callopt.Option) (r *question.BatchAnswerResp, err error)
	GetHistory(ctx context.Context, req *question.HistoryReq, callOptions ...callopt.Option) (r *question.HistoryResp, err error)
	SubmitFeedback(ctx context.Context, req *question.FeedbackReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetRecommendedQuestions(ctx context.Context, userId int64, callOptions ...callopt.Option) (r *common.BaseResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kQAServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kQAServiceClient struct {
	*kClient
}

func (p *kQAServiceClient) AskQuestion(ctx context.Context, req *question.QuestionReq, callOptions ...callopt.Option) (r *question.AnswerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AskQuestion(ctx, req)
}

func (p *kQAServiceClient) BatchAskQuestions(ctx context.Context, req *question.BatchQuestionReq, callOptions ...callopt.Option) (r *question.BatchAnswerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchAskQuestions(ctx, req)
}

func (p *kQAServiceClient) GetHistory(ctx context.Context, req *question.HistoryReq, callOptions ...callopt.Option) (r *question.HistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHistory(ctx, req)
}

func (p *kQAServiceClient) SubmitFeedback(ctx context.Context, req *question.FeedbackReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubmitFeedback(ctx, req)
}

func (p *kQAServiceClient) GetRecommendedQuestions(ctx context.Context, userId int64, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendedQuestions(ctx, userId)
}
