// Code generated by Kitex v0.16.1. DO NOT EDIT.

package datacollectionservice

import (
	collection "Noah/kitex_gen/collection"
	common "Noah/kitex_gen/common"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddDataSource(ctx context.Context, req *collection.AddDataSourceReq, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error)
	UpdateDataSource(ctx context.Context, req *collection.UpdateDataSourceReq, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error)
	DeleteDataSource(ctx context.Context, req *collection.DeleteDataSourceReq, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetDataSource(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error)
	ListDataSources(ctx context.Context, callOptions ...callopt.Option) (r *collection.BatchDataSourceResp, err error)
	CreateTask(ctx context.Context, req *collection.CreateTaskReq, callOptions ...callopt.Option) (r *collection.TaskResp, err error)
	UpdateTask(ctx context.Context, req *collection.UpdateTaskReq, callOptions ...callopt.Option) (r *collection.TaskResp, err error)
	DeleteTask(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetTask(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.TaskResp, err error)
	ListTasks(ctx context.Context, callOptions ...callopt.Option) (r *collection.BatchTaskResp, err error)
	ExecuteTask(ctx context.Context, req *collection.ExecuteTaskReq, callOptions ...callopt.Option) (r *collection.CollectionResultResp, err error)
	StopTask(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *common.BaseResp, err error)
	GetCollectionResult_(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.CollectionResultResp, err error)
	ListCollectionResults(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *collection.BatchCollectionResultResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDataCollectionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDataCollectionServiceClient struct {
	*kClient
}

func (p *kDataCollectionServiceClient) AddDataSource(ctx context.Context, req *collection.AddDataSourceReq, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddDataSource(ctx, req)
}

func (p *kDataCollectionServiceClient) UpdateDataSource(ctx context.Context, req *collection.UpdateDataSourceReq, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDataSource(ctx, req)
}

func (p *kDataCollectionServiceClient) DeleteDataSource(ctx context.Context, req *collection.DeleteDataSourceReq, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDataSource(ctx, req)
}

func (p *kDataCollectionServiceClient) GetDataSource(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.DataSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDataSource(ctx, id)
}

func (p *kDataCollectionServiceClient) ListDataSources(ctx context.Context, callOptions ...callopt.Option) (r *collection.BatchDataSourceResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDataSources(ctx)
}

func (p *kDataCollectionServiceClient) CreateTask(ctx context.Context, req *collection.CreateTaskReq, callOptions ...callopt.Option) (r *collection.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTask(ctx, req)
}

func (p *kDataCollectionServiceClient) UpdateTask(ctx context.Context, req *collection.UpdateTaskReq, callOptions ...callopt.Option) (r *collection.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTask(ctx, req)
}

func (p *kDataCollectionServiceClient) DeleteTask(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTask(ctx, taskId)
}

func (p *kDataCollectionServiceClient) GetTask(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.TaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTask(ctx, id)
}

func (p *kDataCollectionServiceClient) ListTasks(ctx context.Context, callOptions ...callopt.Option) (r *collection.BatchTaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTasks(ctx)
}

func (p *kDataCollectionServiceClient) ExecuteTask(ctx context.Context, req *collection.ExecuteTaskReq, callOptions ...callopt.Option) (r *collection.CollectionResultResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExecuteTask(ctx, req)
}

func (p *kDataCollectionServiceClient) StopTask(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *common.BaseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StopTask(ctx, taskId)
}

func (p *kDataCollectionServiceClient) GetCollectionResult_(ctx context.Context, id string, callOptions ...callopt.Option) (r *collection.CollectionResultResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCollectionResult_(ctx, id)
}

func (p *kDataCollectionServiceClient) ListCollectionResults(ctx context.Context, taskId string, callOptions ...callopt.Option) (r *collection.BatchCollectionResultResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCollectionResults(ctx, taskId)
}
